namespace Pia_2._0
{
    partial class Editar_Paciente
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Editar_Paciente));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties65 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties66 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties67 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties68 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties69 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties70 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties71 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties72 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            DataGridViewCellStyle dataGridViewCellStyle7 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle8 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle9 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle10 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle11 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle12 = new DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties73 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties74 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties75 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties76 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties77 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties78 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties79 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties80 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties81 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties82 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties83 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties84 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties85 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties86 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties87 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties88 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties89 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties90 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties91 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties92 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties93 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties94 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties95 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties96 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            panel1 = new Panel();
            bunifuLabel16 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuDropdown1 = new Bunifu.UI.WinForms.BunifuDropdown();
            bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox8 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel12 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox9 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel13 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox10 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel14 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox11 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel15 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox12 = new Bunifu.UI.WinForms.BunifuTextBox();
            rjButton2 = new PIA_1._0.RJButton();
            rjButton1 = new PIA_1._0.RJButton();
            bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            richTextBox1 = new RichTextBox();
            bunifuDataGridView2 = new Bunifu.UI.WinForms.BunifuDataGridView();
            Alergias = new DataGridViewTextBoxColumn();
            bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            Enfermedades = new DataGridViewTextBoxColumn();
            comboBox1 = new ComboBox();
            bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuDatePicker1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox5 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox6 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox7 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox4 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox3 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)bunifuDataGridView2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)bunifuDataGridView1).BeginInit();
            SuspendLayout();
            // 
            // panel1
            // 
            panel1.AutoScroll = true;
            panel1.Controls.Add(bunifuLabel16);
            panel1.Controls.Add(bunifuDropdown1);
            panel1.Controls.Add(bunifuLabel8);
            panel1.Controls.Add(bunifuTextBox2);
            panel1.Controls.Add(bunifuLabel11);
            panel1.Controls.Add(bunifuTextBox8);
            panel1.Controls.Add(bunifuLabel12);
            panel1.Controls.Add(bunifuTextBox9);
            panel1.Controls.Add(bunifuLabel13);
            panel1.Controls.Add(bunifuTextBox10);
            panel1.Controls.Add(bunifuLabel14);
            panel1.Controls.Add(bunifuTextBox11);
            panel1.Controls.Add(bunifuLabel15);
            panel1.Controls.Add(bunifuTextBox12);
            panel1.Controls.Add(rjButton2);
            panel1.Controls.Add(rjButton1);
            panel1.Controls.Add(bunifuLabel7);
            panel1.Controls.Add(richTextBox1);
            panel1.Controls.Add(bunifuDataGridView2);
            panel1.Controls.Add(bunifuDataGridView1);
            panel1.Controls.Add(comboBox1);
            panel1.Controls.Add(bunifuLabel10);
            panel1.Controls.Add(bunifuDatePicker1);
            panel1.Controls.Add(bunifuLabel9);
            panel1.Controls.Add(bunifuLabel4);
            panel1.Controls.Add(bunifuTextBox5);
            panel1.Controls.Add(bunifuLabel5);
            panel1.Controls.Add(bunifuTextBox6);
            panel1.Controls.Add(bunifuLabel6);
            panel1.Controls.Add(bunifuTextBox7);
            panel1.Controls.Add(bunifuLabel3);
            panel1.Controls.Add(bunifuTextBox4);
            panel1.Controls.Add(bunifuLabel2);
            panel1.Controls.Add(bunifuTextBox3);
            panel1.Controls.Add(bunifuLabel1);
            panel1.Controls.Add(bunifuGradientPanel1);
            panel1.Controls.Add(bunifuTextBox1);
            panel1.Location = new Point(2, 35);
            panel1.Name = "panel1";
            panel1.Size = new Size(557, 504);
            panel1.TabIndex = 1;
            // 
            // bunifuLabel16
            // 
            bunifuLabel16.AllowParentOverrides = false;
            bunifuLabel16.AutoEllipsis = false;
            bunifuLabel16.CursorType = Cursors.Default;
            bunifuLabel16.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel16.Location = new Point(399, 679);
            bunifuLabel16.Name = "bunifuLabel16";
            bunifuLabel16.RightToLeft = RightToLeft.No;
            bunifuLabel16.Size = new Size(49, 21);
            bunifuLabel16.TabIndex = 42;
            bunifuLabel16.Text = "Activo";
            bunifuLabel16.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel16.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuDropdown1
            // 
            bunifuDropdown1.BackColor = Color.Transparent;
            bunifuDropdown1.BackgroundColor = Color.White;
            bunifuDropdown1.BorderColor = Color.Silver;
            bunifuDropdown1.BorderRadius = 1;
            bunifuDropdown1.Color = Color.Silver;
            bunifuDropdown1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            bunifuDropdown1.DisabledBackColor = Color.FromArgb(240, 240, 240);
            bunifuDropdown1.DisabledBorderColor = Color.FromArgb(204, 204, 204);
            bunifuDropdown1.DisabledColor = Color.FromArgb(240, 240, 240);
            bunifuDropdown1.DisabledForeColor = Color.FromArgb(109, 109, 109);
            bunifuDropdown1.DisabledIndicatorColor = Color.DarkGray;
            bunifuDropdown1.DrawMode = DrawMode.OwnerDrawFixed;
            bunifuDropdown1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            bunifuDropdown1.DropDownStyle = ComboBoxStyle.DropDownList;
            bunifuDropdown1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            bunifuDropdown1.FillDropDown = true;
            bunifuDropdown1.FillIndicator = false;
            bunifuDropdown1.FlatStyle = FlatStyle.Flat;
            bunifuDropdown1.Font = new Font("Segoe UI", 9F);
            bunifuDropdown1.ForeColor = Color.Black;
            bunifuDropdown1.FormattingEnabled = true;
            bunifuDropdown1.Icon = null;
            bunifuDropdown1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            bunifuDropdown1.IndicatorColor = Color.DarkGray;
            bunifuDropdown1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            bunifuDropdown1.IndicatorThickness = 2;
            bunifuDropdown1.IsDropdownOpened = false;
            bunifuDropdown1.ItemBackColor = Color.White;
            bunifuDropdown1.ItemBorderColor = Color.White;
            bunifuDropdown1.ItemForeColor = Color.Black;
            bunifuDropdown1.ItemHeight = 26;
            bunifuDropdown1.ItemHighLightColor = Color.DodgerBlue;
            bunifuDropdown1.ItemHighLightForeColor = Color.White;
            bunifuDropdown1.Items.AddRange(new object[] { "Activo", "Inactivo" });
            bunifuDropdown1.ItemTopMargin = 3;
            bunifuDropdown1.Location = new Point(399, 706);
            bunifuDropdown1.Name = "bunifuDropdown1";
            bunifuDropdown1.Size = new Size(121, 32);
            bunifuDropdown1.TabIndex = 41;
            bunifuDropdown1.Text = null;
            bunifuDropdown1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            bunifuDropdown1.TextLeftMargin = 5;
            // 
            // bunifuLabel8
            // 
            bunifuLabel8.AllowParentOverrides = false;
            bunifuLabel8.AutoEllipsis = false;
            bunifuLabel8.CursorType = Cursors.Default;
            bunifuLabel8.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel8.Location = new Point(357, 365);
            bunifuLabel8.Name = "bunifuLabel8";
            bunifuLabel8.RightToLeft = RightToLeft.No;
            bunifuLabel8.Size = new Size(106, 21);
            bunifuLabel8.TabIndex = 40;
            bunifuLabel8.Text = "Codigo Postal";
            bunifuLabel8.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox2
            // 
            bunifuTextBox2.AcceptsReturn = false;
            bunifuTextBox2.AcceptsTab = false;
            bunifuTextBox2.AnimationSpeed = 200;
            bunifuTextBox2.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox2.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox2.AutoSizeHeight = true;
            bunifuTextBox2.BackColor = Color.Transparent;
            bunifuTextBox2.BackgroundImage = (Image)resources.GetObject("bunifuTextBox2.BackgroundImage");
            bunifuTextBox2.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox2.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox2.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox2.BorderColorIdle = Color.Silver;
            bunifuTextBox2.BorderRadius = 1;
            bunifuTextBox2.BorderThickness = 1;
            bunifuTextBox2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox2.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox2.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox2.DefaultText = "";
            bunifuTextBox2.FillColor = Color.White;
            bunifuTextBox2.HideSelection = true;
            bunifuTextBox2.IconLeft = null;
            bunifuTextBox2.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox2.IconPadding = 10;
            bunifuTextBox2.IconRight = null;
            bunifuTextBox2.IconRightCursor = Cursors.IBeam;
            bunifuTextBox2.Location = new Point(357, 392);
            bunifuTextBox2.MaxLength = 32767;
            bunifuTextBox2.MinimumSize = new Size(1, 1);
            bunifuTextBox2.Modified = false;
            bunifuTextBox2.Multiline = false;
            bunifuTextBox2.Name = "bunifuTextBox2";
            stateProperties49.BorderColor = Color.DodgerBlue;
            stateProperties49.FillColor = Color.Empty;
            stateProperties49.ForeColor = Color.Empty;
            stateProperties49.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties50.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties50.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties50.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox2.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties51.FillColor = Color.Empty;
            stateProperties51.ForeColor = Color.Empty;
            stateProperties51.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = Color.Silver;
            stateProperties52.FillColor = Color.White;
            stateProperties52.ForeColor = Color.Empty;
            stateProperties52.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnIdleState = stateProperties52;
            bunifuTextBox2.Padding = new Padding(3);
            bunifuTextBox2.PasswordChar = '\0';
            bunifuTextBox2.PlaceholderForeColor = Color.Silver;
            bunifuTextBox2.PlaceholderText = "Enter text";
            bunifuTextBox2.ReadOnly = false;
            bunifuTextBox2.ScrollBars = ScrollBars.None;
            bunifuTextBox2.SelectedText = "";
            bunifuTextBox2.SelectionLength = 0;
            bunifuTextBox2.SelectionStart = 0;
            bunifuTextBox2.ShortcutsEnabled = true;
            bunifuTextBox2.Size = new Size(151, 39);
            bunifuTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox2.TabIndex = 39;
            bunifuTextBox2.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox2.TextMarginBottom = 0;
            bunifuTextBox2.TextMarginLeft = 3;
            bunifuTextBox2.TextMarginTop = 1;
            bunifuTextBox2.TextPlaceholder = "Enter text";
            bunifuTextBox2.UseSystemPasswordChar = false;
            bunifuTextBox2.WordWrap = true;
            // 
            // bunifuLabel11
            // 
            bunifuLabel11.AllowParentOverrides = false;
            bunifuLabel11.AutoEllipsis = false;
            bunifuLabel11.CursorType = Cursors.Default;
            bunifuLabel11.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel11.Location = new Point(185, 365);
            bunifuLabel11.Name = "bunifuLabel11";
            bunifuLabel11.RightToLeft = RightToLeft.No;
            bunifuLabel11.Size = new Size(51, 21);
            bunifuLabel11.TabIndex = 38;
            bunifuLabel11.Text = "Estado";
            bunifuLabel11.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox8
            // 
            bunifuTextBox8.AcceptsReturn = false;
            bunifuTextBox8.AcceptsTab = false;
            bunifuTextBox8.AnimationSpeed = 200;
            bunifuTextBox8.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox8.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox8.AutoSizeHeight = true;
            bunifuTextBox8.BackColor = Color.Transparent;
            bunifuTextBox8.BackgroundImage = (Image)resources.GetObject("bunifuTextBox8.BackgroundImage");
            bunifuTextBox8.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox8.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox8.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox8.BorderColorIdle = Color.Silver;
            bunifuTextBox8.BorderRadius = 1;
            bunifuTextBox8.BorderThickness = 1;
            bunifuTextBox8.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox8.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox8.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox8.DefaultText = "";
            bunifuTextBox8.FillColor = Color.White;
            bunifuTextBox8.HideSelection = true;
            bunifuTextBox8.IconLeft = null;
            bunifuTextBox8.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox8.IconPadding = 10;
            bunifuTextBox8.IconRight = null;
            bunifuTextBox8.IconRightCursor = Cursors.IBeam;
            bunifuTextBox8.Location = new Point(185, 392);
            bunifuTextBox8.MaxLength = 32767;
            bunifuTextBox8.MinimumSize = new Size(1, 1);
            bunifuTextBox8.Modified = false;
            bunifuTextBox8.Multiline = false;
            bunifuTextBox8.Name = "bunifuTextBox8";
            stateProperties53.BorderColor = Color.DodgerBlue;
            stateProperties53.FillColor = Color.Empty;
            stateProperties53.ForeColor = Color.Empty;
            stateProperties53.PlaceholderForeColor = Color.Empty;
            bunifuTextBox8.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties54.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties54.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties54.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox8.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties55.FillColor = Color.Empty;
            stateProperties55.ForeColor = Color.Empty;
            stateProperties55.PlaceholderForeColor = Color.Empty;
            bunifuTextBox8.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = Color.Silver;
            stateProperties56.FillColor = Color.White;
            stateProperties56.ForeColor = Color.Empty;
            stateProperties56.PlaceholderForeColor = Color.Empty;
            bunifuTextBox8.OnIdleState = stateProperties56;
            bunifuTextBox8.Padding = new Padding(3);
            bunifuTextBox8.PasswordChar = '\0';
            bunifuTextBox8.PlaceholderForeColor = Color.Silver;
            bunifuTextBox8.PlaceholderText = "Enter text";
            bunifuTextBox8.ReadOnly = false;
            bunifuTextBox8.ScrollBars = ScrollBars.None;
            bunifuTextBox8.SelectedText = "";
            bunifuTextBox8.SelectionLength = 0;
            bunifuTextBox8.SelectionStart = 0;
            bunifuTextBox8.ShortcutsEnabled = true;
            bunifuTextBox8.Size = new Size(151, 39);
            bunifuTextBox8.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox8.TabIndex = 37;
            bunifuTextBox8.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox8.TextMarginBottom = 0;
            bunifuTextBox8.TextMarginLeft = 3;
            bunifuTextBox8.TextMarginTop = 1;
            bunifuTextBox8.TextPlaceholder = "Enter text";
            bunifuTextBox8.UseSystemPasswordChar = false;
            bunifuTextBox8.WordWrap = true;
            // 
            // bunifuLabel12
            // 
            bunifuLabel12.AllowParentOverrides = false;
            bunifuLabel12.AutoEllipsis = false;
            bunifuLabel12.CursorType = Cursors.Default;
            bunifuLabel12.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel12.Location = new Point(12, 365);
            bunifuLabel12.Name = "bunifuLabel12";
            bunifuLabel12.RightToLeft = RightToLeft.No;
            bunifuLabel12.Size = new Size(54, 21);
            bunifuLabel12.TabIndex = 36;
            bunifuLabel12.Text = "Ciudad";
            bunifuLabel12.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel12.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox9
            // 
            bunifuTextBox9.AcceptsReturn = false;
            bunifuTextBox9.AcceptsTab = false;
            bunifuTextBox9.AnimationSpeed = 200;
            bunifuTextBox9.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox9.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox9.AutoSizeHeight = true;
            bunifuTextBox9.BackColor = Color.Transparent;
            bunifuTextBox9.BackgroundImage = (Image)resources.GetObject("bunifuTextBox9.BackgroundImage");
            bunifuTextBox9.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox9.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox9.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox9.BorderColorIdle = Color.Silver;
            bunifuTextBox9.BorderRadius = 1;
            bunifuTextBox9.BorderThickness = 1;
            bunifuTextBox9.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox9.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox9.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox9.DefaultText = "";
            bunifuTextBox9.FillColor = Color.White;
            bunifuTextBox9.HideSelection = true;
            bunifuTextBox9.IconLeft = null;
            bunifuTextBox9.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox9.IconPadding = 10;
            bunifuTextBox9.IconRight = null;
            bunifuTextBox9.IconRightCursor = Cursors.IBeam;
            bunifuTextBox9.Location = new Point(12, 392);
            bunifuTextBox9.MaxLength = 32767;
            bunifuTextBox9.MinimumSize = new Size(1, 1);
            bunifuTextBox9.Modified = false;
            bunifuTextBox9.Multiline = false;
            bunifuTextBox9.Name = "bunifuTextBox9";
            stateProperties57.BorderColor = Color.DodgerBlue;
            stateProperties57.FillColor = Color.Empty;
            stateProperties57.ForeColor = Color.Empty;
            stateProperties57.PlaceholderForeColor = Color.Empty;
            bunifuTextBox9.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties58.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties58.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties58.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox9.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties59.FillColor = Color.Empty;
            stateProperties59.ForeColor = Color.Empty;
            stateProperties59.PlaceholderForeColor = Color.Empty;
            bunifuTextBox9.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = Color.Silver;
            stateProperties60.FillColor = Color.White;
            stateProperties60.ForeColor = Color.Empty;
            stateProperties60.PlaceholderForeColor = Color.Empty;
            bunifuTextBox9.OnIdleState = stateProperties60;
            bunifuTextBox9.Padding = new Padding(3);
            bunifuTextBox9.PasswordChar = '\0';
            bunifuTextBox9.PlaceholderForeColor = Color.Silver;
            bunifuTextBox9.PlaceholderText = "Enter text";
            bunifuTextBox9.ReadOnly = false;
            bunifuTextBox9.ScrollBars = ScrollBars.None;
            bunifuTextBox9.SelectedText = "";
            bunifuTextBox9.SelectionLength = 0;
            bunifuTextBox9.SelectionStart = 0;
            bunifuTextBox9.ShortcutsEnabled = true;
            bunifuTextBox9.Size = new Size(151, 39);
            bunifuTextBox9.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox9.TabIndex = 35;
            bunifuTextBox9.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox9.TextMarginBottom = 0;
            bunifuTextBox9.TextMarginLeft = 3;
            bunifuTextBox9.TextMarginTop = 1;
            bunifuTextBox9.TextPlaceholder = "Enter text";
            bunifuTextBox9.UseSystemPasswordChar = false;
            bunifuTextBox9.WordWrap = true;
            // 
            // bunifuLabel13
            // 
            bunifuLabel13.AllowParentOverrides = false;
            bunifuLabel13.AutoEllipsis = false;
            bunifuLabel13.CursorType = Cursors.Default;
            bunifuLabel13.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel13.Location = new Point(357, 280);
            bunifuLabel13.Name = "bunifuLabel13";
            bunifuLabel13.RightToLeft = RightToLeft.No;
            bunifuLabel13.Size = new Size(59, 21);
            bunifuLabel13.TabIndex = 34;
            bunifuLabel13.Text = "Colonia";
            bunifuLabel13.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel13.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox10
            // 
            bunifuTextBox10.AcceptsReturn = false;
            bunifuTextBox10.AcceptsTab = false;
            bunifuTextBox10.AnimationSpeed = 200;
            bunifuTextBox10.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox10.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox10.AutoSizeHeight = true;
            bunifuTextBox10.BackColor = Color.Transparent;
            bunifuTextBox10.BackgroundImage = (Image)resources.GetObject("bunifuTextBox10.BackgroundImage");
            bunifuTextBox10.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox10.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox10.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox10.BorderColorIdle = Color.Silver;
            bunifuTextBox10.BorderRadius = 1;
            bunifuTextBox10.BorderThickness = 1;
            bunifuTextBox10.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox10.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox10.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox10.DefaultText = "";
            bunifuTextBox10.FillColor = Color.White;
            bunifuTextBox10.HideSelection = true;
            bunifuTextBox10.IconLeft = null;
            bunifuTextBox10.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox10.IconPadding = 10;
            bunifuTextBox10.IconRight = null;
            bunifuTextBox10.IconRightCursor = Cursors.IBeam;
            bunifuTextBox10.Location = new Point(357, 307);
            bunifuTextBox10.MaxLength = 32767;
            bunifuTextBox10.MinimumSize = new Size(1, 1);
            bunifuTextBox10.Modified = false;
            bunifuTextBox10.Multiline = false;
            bunifuTextBox10.Name = "bunifuTextBox10";
            stateProperties61.BorderColor = Color.DodgerBlue;
            stateProperties61.FillColor = Color.Empty;
            stateProperties61.ForeColor = Color.Empty;
            stateProperties61.PlaceholderForeColor = Color.Empty;
            bunifuTextBox10.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties62.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties62.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties62.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox10.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties63.FillColor = Color.Empty;
            stateProperties63.ForeColor = Color.Empty;
            stateProperties63.PlaceholderForeColor = Color.Empty;
            bunifuTextBox10.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = Color.Silver;
            stateProperties64.FillColor = Color.White;
            stateProperties64.ForeColor = Color.Empty;
            stateProperties64.PlaceholderForeColor = Color.Empty;
            bunifuTextBox10.OnIdleState = stateProperties64;
            bunifuTextBox10.Padding = new Padding(3);
            bunifuTextBox10.PasswordChar = '\0';
            bunifuTextBox10.PlaceholderForeColor = Color.Silver;
            bunifuTextBox10.PlaceholderText = "Enter text";
            bunifuTextBox10.ReadOnly = false;
            bunifuTextBox10.ScrollBars = ScrollBars.None;
            bunifuTextBox10.SelectedText = "";
            bunifuTextBox10.SelectionLength = 0;
            bunifuTextBox10.SelectionStart = 0;
            bunifuTextBox10.ShortcutsEnabled = true;
            bunifuTextBox10.Size = new Size(151, 39);
            bunifuTextBox10.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox10.TabIndex = 33;
            bunifuTextBox10.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox10.TextMarginBottom = 0;
            bunifuTextBox10.TextMarginLeft = 3;
            bunifuTextBox10.TextMarginTop = 1;
            bunifuTextBox10.TextPlaceholder = "Enter text";
            bunifuTextBox10.UseSystemPasswordChar = false;
            bunifuTextBox10.WordWrap = true;
            // 
            // bunifuLabel14
            // 
            bunifuLabel14.AllowParentOverrides = false;
            bunifuLabel14.AutoEllipsis = false;
            bunifuLabel14.CursorType = Cursors.Default;
            bunifuLabel14.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel14.Location = new Point(185, 280);
            bunifuLabel14.Name = "bunifuLabel14";
            bunifuLabel14.RightToLeft = RightToLeft.No;
            bunifuLabel14.Size = new Size(63, 21);
            bunifuLabel14.TabIndex = 32;
            bunifuLabel14.Text = "Numero";
            bunifuLabel14.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel14.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox11
            // 
            bunifuTextBox11.AcceptsReturn = false;
            bunifuTextBox11.AcceptsTab = false;
            bunifuTextBox11.AnimationSpeed = 200;
            bunifuTextBox11.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox11.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox11.AutoSizeHeight = true;
            bunifuTextBox11.BackColor = Color.Transparent;
            bunifuTextBox11.BackgroundImage = (Image)resources.GetObject("bunifuTextBox11.BackgroundImage");
            bunifuTextBox11.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox11.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox11.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox11.BorderColorIdle = Color.Silver;
            bunifuTextBox11.BorderRadius = 1;
            bunifuTextBox11.BorderThickness = 1;
            bunifuTextBox11.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox11.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox11.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox11.DefaultText = "";
            bunifuTextBox11.FillColor = Color.White;
            bunifuTextBox11.HideSelection = true;
            bunifuTextBox11.IconLeft = null;
            bunifuTextBox11.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox11.IconPadding = 10;
            bunifuTextBox11.IconRight = null;
            bunifuTextBox11.IconRightCursor = Cursors.IBeam;
            bunifuTextBox11.Location = new Point(185, 307);
            bunifuTextBox11.MaxLength = 32767;
            bunifuTextBox11.MinimumSize = new Size(1, 1);
            bunifuTextBox11.Modified = false;
            bunifuTextBox11.Multiline = false;
            bunifuTextBox11.Name = "bunifuTextBox11";
            stateProperties65.BorderColor = Color.DodgerBlue;
            stateProperties65.FillColor = Color.Empty;
            stateProperties65.ForeColor = Color.Empty;
            stateProperties65.PlaceholderForeColor = Color.Empty;
            bunifuTextBox11.OnActiveState = stateProperties65;
            stateProperties66.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties66.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties66.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties66.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox11.OnDisabledState = stateProperties66;
            stateProperties67.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties67.FillColor = Color.Empty;
            stateProperties67.ForeColor = Color.Empty;
            stateProperties67.PlaceholderForeColor = Color.Empty;
            bunifuTextBox11.OnHoverState = stateProperties67;
            stateProperties68.BorderColor = Color.Silver;
            stateProperties68.FillColor = Color.White;
            stateProperties68.ForeColor = Color.Empty;
            stateProperties68.PlaceholderForeColor = Color.Empty;
            bunifuTextBox11.OnIdleState = stateProperties68;
            bunifuTextBox11.Padding = new Padding(3);
            bunifuTextBox11.PasswordChar = '\0';
            bunifuTextBox11.PlaceholderForeColor = Color.Silver;
            bunifuTextBox11.PlaceholderText = "Enter text";
            bunifuTextBox11.ReadOnly = false;
            bunifuTextBox11.ScrollBars = ScrollBars.None;
            bunifuTextBox11.SelectedText = "";
            bunifuTextBox11.SelectionLength = 0;
            bunifuTextBox11.SelectionStart = 0;
            bunifuTextBox11.ShortcutsEnabled = true;
            bunifuTextBox11.Size = new Size(151, 39);
            bunifuTextBox11.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox11.TabIndex = 31;
            bunifuTextBox11.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox11.TextMarginBottom = 0;
            bunifuTextBox11.TextMarginLeft = 3;
            bunifuTextBox11.TextMarginTop = 1;
            bunifuTextBox11.TextPlaceholder = "Enter text";
            bunifuTextBox11.UseSystemPasswordChar = false;
            bunifuTextBox11.WordWrap = true;
            // 
            // bunifuLabel15
            // 
            bunifuLabel15.AllowParentOverrides = false;
            bunifuLabel15.AutoEllipsis = false;
            bunifuLabel15.CursorType = Cursors.Default;
            bunifuLabel15.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel15.Location = new Point(12, 280);
            bunifuLabel15.Name = "bunifuLabel15";
            bunifuLabel15.RightToLeft = RightToLeft.No;
            bunifuLabel15.Size = new Size(38, 21);
            bunifuLabel15.TabIndex = 30;
            bunifuLabel15.Text = "Calle";
            bunifuLabel15.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel15.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox12
            // 
            bunifuTextBox12.AcceptsReturn = false;
            bunifuTextBox12.AcceptsTab = false;
            bunifuTextBox12.AnimationSpeed = 200;
            bunifuTextBox12.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox12.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox12.AutoSizeHeight = true;
            bunifuTextBox12.BackColor = Color.Transparent;
            bunifuTextBox12.BackgroundImage = (Image)resources.GetObject("bunifuTextBox12.BackgroundImage");
            bunifuTextBox12.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox12.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox12.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox12.BorderColorIdle = Color.Silver;
            bunifuTextBox12.BorderRadius = 1;
            bunifuTextBox12.BorderThickness = 1;
            bunifuTextBox12.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox12.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox12.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox12.DefaultText = "";
            bunifuTextBox12.FillColor = Color.White;
            bunifuTextBox12.HideSelection = true;
            bunifuTextBox12.IconLeft = null;
            bunifuTextBox12.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox12.IconPadding = 10;
            bunifuTextBox12.IconRight = null;
            bunifuTextBox12.IconRightCursor = Cursors.IBeam;
            bunifuTextBox12.Location = new Point(12, 307);
            bunifuTextBox12.MaxLength = 32767;
            bunifuTextBox12.MinimumSize = new Size(1, 1);
            bunifuTextBox12.Modified = false;
            bunifuTextBox12.Multiline = false;
            bunifuTextBox12.Name = "bunifuTextBox12";
            stateProperties69.BorderColor = Color.DodgerBlue;
            stateProperties69.FillColor = Color.Empty;
            stateProperties69.ForeColor = Color.Empty;
            stateProperties69.PlaceholderForeColor = Color.Empty;
            bunifuTextBox12.OnActiveState = stateProperties69;
            stateProperties70.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties70.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties70.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties70.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox12.OnDisabledState = stateProperties70;
            stateProperties71.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties71.FillColor = Color.Empty;
            stateProperties71.ForeColor = Color.Empty;
            stateProperties71.PlaceholderForeColor = Color.Empty;
            bunifuTextBox12.OnHoverState = stateProperties71;
            stateProperties72.BorderColor = Color.Silver;
            stateProperties72.FillColor = Color.White;
            stateProperties72.ForeColor = Color.Empty;
            stateProperties72.PlaceholderForeColor = Color.Empty;
            bunifuTextBox12.OnIdleState = stateProperties72;
            bunifuTextBox12.Padding = new Padding(3);
            bunifuTextBox12.PasswordChar = '\0';
            bunifuTextBox12.PlaceholderForeColor = Color.Silver;
            bunifuTextBox12.PlaceholderText = "Enter text";
            bunifuTextBox12.ReadOnly = false;
            bunifuTextBox12.ScrollBars = ScrollBars.None;
            bunifuTextBox12.SelectedText = "";
            bunifuTextBox12.SelectionLength = 0;
            bunifuTextBox12.SelectionStart = 0;
            bunifuTextBox12.ShortcutsEnabled = true;
            bunifuTextBox12.Size = new Size(151, 39);
            bunifuTextBox12.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox12.TabIndex = 29;
            bunifuTextBox12.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox12.TextMarginBottom = 0;
            bunifuTextBox12.TextMarginLeft = 3;
            bunifuTextBox12.TextMarginTop = 1;
            bunifuTextBox12.TextPlaceholder = "Enter text";
            bunifuTextBox12.UseSystemPasswordChar = false;
            bunifuTextBox12.WordWrap = true;
            // 
            // rjButton2
            // 
            rjButton2.BackColor = Color.Gray;
            rjButton2.BackgroundColor = Color.Gray;
            rjButton2.BorderColor = Color.PaleVioletRed;
            rjButton2.BorderRadius = 15;
            rjButton2.BorderSize = 0;
            rjButton2.FlatAppearance.BorderSize = 0;
            rjButton2.FlatStyle = FlatStyle.Flat;
            rjButton2.Font = new Font("Segoe UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            rjButton2.ForeColor = Color.White;
            rjButton2.Location = new Point(214, 943);
            rjButton2.Name = "rjButton2";
            rjButton2.Size = new Size(150, 40);
            rjButton2.TabIndex = 28;
            rjButton2.Text = "Cancelar";
            rjButton2.TextColor = Color.White;
            rjButton2.UseVisualStyleBackColor = false;
            rjButton2.Click += rjButton2_Click_1;
            // 
            // rjButton1
            // 
            rjButton1.BackColor = Color.RoyalBlue;
            rjButton1.BackgroundColor = Color.RoyalBlue;
            rjButton1.BorderColor = Color.PaleVioletRed;
            rjButton1.BorderRadius = 15;
            rjButton1.BorderSize = 0;
            rjButton1.FlatAppearance.BorderSize = 0;
            rjButton1.FlatStyle = FlatStyle.Flat;
            rjButton1.Font = new Font("Segoe UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            rjButton1.ForeColor = Color.White;
            rjButton1.Location = new Point(370, 943);
            rjButton1.Name = "rjButton1";
            rjButton1.Size = new Size(150, 40);
            rjButton1.TabIndex = 0;
            rjButton1.Text = "Agregar";
            rjButton1.TextColor = Color.White;
            rjButton1.UseVisualStyleBackColor = false;
            rjButton1.Click += rjButton1_Click_1;
            // 
            // bunifuLabel7
            // 
            bunifuLabel7.AllowParentOverrides = false;
            bunifuLabel7.AutoEllipsis = false;
            bunifuLabel7.CursorType = Cursors.Default;
            bunifuLabel7.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel7.Location = new Point(12, 679);
            bunifuLabel7.Name = "bunifuLabel7";
            bunifuLabel7.RightToLeft = RightToLeft.No;
            bunifuLabel7.Size = new Size(111, 21);
            bunifuLabel7.TabIndex = 27;
            bunifuLabel7.Text = "Observaciones";
            bunifuLabel7.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // richTextBox1
            // 
            richTextBox1.Location = new Point(12, 706);
            richTextBox1.Name = "richTextBox1";
            richTextBox1.Size = new Size(381, 208);
            richTextBox1.TabIndex = 26;
            richTextBox1.Text = "";
            // 
            // bunifuDataGridView2
            // 
            bunifuDataGridView2.AllowCustomTheming = false;
            dataGridViewCellStyle7.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle7.ForeColor = Color.Black;
            bunifuDataGridView2.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle7;
            bunifuDataGridView2.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            bunifuDataGridView2.BorderStyle = BorderStyle.None;
            bunifuDataGridView2.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            bunifuDataGridView2.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle8.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle8.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle8.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle8.ForeColor = Color.White;
            dataGridViewCellStyle8.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle8.SelectionForeColor = Color.White;
            dataGridViewCellStyle8.WrapMode = DataGridViewTriState.True;
            bunifuDataGridView2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle8;
            bunifuDataGridView2.ColumnHeadersHeight = 40;
            bunifuDataGridView2.Columns.AddRange(new DataGridViewColumn[] { Alergias });
            bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            bunifuDataGridView2.CurrentTheme.BackColor = Color.White;
            bunifuDataGridView2.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            bunifuDataGridView2.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            bunifuDataGridView2.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            bunifuDataGridView2.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            bunifuDataGridView2.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            bunifuDataGridView2.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            bunifuDataGridView2.CurrentTheme.Name = null;
            bunifuDataGridView2.CurrentTheme.RowsStyle.BackColor = Color.White;
            bunifuDataGridView2.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            bunifuDataGridView2.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            bunifuDataGridView2.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            bunifuDataGridView2.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle9.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle9.BackColor = Color.White;
            dataGridViewCellStyle9.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle9.ForeColor = Color.Black;
            dataGridViewCellStyle9.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle9.SelectionForeColor = Color.Black;
            dataGridViewCellStyle9.WrapMode = DataGridViewTriState.False;
            bunifuDataGridView2.DefaultCellStyle = dataGridViewCellStyle9;
            bunifuDataGridView2.EnableHeadersVisualStyles = false;
            bunifuDataGridView2.GridColor = Color.FromArgb(221, 238, 255);
            bunifuDataGridView2.HeaderBackColor = Color.DodgerBlue;
            bunifuDataGridView2.HeaderBgColor = Color.Empty;
            bunifuDataGridView2.HeaderForeColor = Color.White;
            bunifuDataGridView2.Location = new Point(293, 499);
            bunifuDataGridView2.Name = "bunifuDataGridView2";
            bunifuDataGridView2.RowHeadersVisible = false;
            bunifuDataGridView2.RowTemplate.Height = 40;
            bunifuDataGridView2.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            bunifuDataGridView2.Size = new Size(227, 150);
            bunifuDataGridView2.TabIndex = 25;
            bunifuDataGridView2.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // Alergias
            // 
            Alergias.HeaderText = "Alergias";
            Alergias.Name = "Alergias";
            // 
            // bunifuDataGridView1
            // 
            bunifuDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle10.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle10.ForeColor = Color.Black;
            bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle10;
            bunifuDataGridView1.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            bunifuDataGridView1.BorderStyle = BorderStyle.None;
            bunifuDataGridView1.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            bunifuDataGridView1.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle11.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle11.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle11.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle11.ForeColor = Color.White;
            dataGridViewCellStyle11.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle11.SelectionForeColor = Color.White;
            dataGridViewCellStyle11.WrapMode = DataGridViewTriState.True;
            bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle11;
            bunifuDataGridView1.ColumnHeadersHeight = 40;
            bunifuDataGridView1.Columns.AddRange(new DataGridViewColumn[] { Enfermedades });
            bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            bunifuDataGridView1.CurrentTheme.BackColor = Color.White;
            bunifuDataGridView1.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            bunifuDataGridView1.CurrentTheme.Name = null;
            bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = Color.White;
            bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle12.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle12.BackColor = Color.White;
            dataGridViewCellStyle12.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle12.ForeColor = Color.Black;
            dataGridViewCellStyle12.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle12.SelectionForeColor = Color.Black;
            dataGridViewCellStyle12.WrapMode = DataGridViewTriState.False;
            bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle12;
            bunifuDataGridView1.EnableHeadersVisualStyles = false;
            bunifuDataGridView1.GridColor = Color.FromArgb(221, 238, 255);
            bunifuDataGridView1.HeaderBackColor = Color.DodgerBlue;
            bunifuDataGridView1.HeaderBgColor = Color.Empty;
            bunifuDataGridView1.HeaderForeColor = Color.White;
            bunifuDataGridView1.Location = new Point(12, 499);
            bunifuDataGridView1.Name = "bunifuDataGridView1";
            bunifuDataGridView1.RowHeadersVisible = false;
            bunifuDataGridView1.RowTemplate.Height = 40;
            bunifuDataGridView1.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            bunifuDataGridView1.Size = new Size(227, 150);
            bunifuDataGridView1.TabIndex = 24;
            bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // Enfermedades
            // 
            Enfermedades.HeaderText = "Enfermedades";
            Enfermedades.Name = "Enfermedades";
            // 
            // comboBox1
            // 
            comboBox1.FormattingEnabled = true;
            comboBox1.Items.AddRange(new object[] { "Masculino", "Femenino" });
            comboBox1.Location = new Point(12, 217);
            comboBox1.Name = "comboBox1";
            comboBox1.Size = new Size(151, 23);
            comboBox1.TabIndex = 23;
            // 
            // bunifuLabel10
            // 
            bunifuLabel10.AllowParentOverrides = false;
            bunifuLabel10.AutoEllipsis = false;
            bunifuLabel10.CursorType = Cursors.Default;
            bunifuLabel10.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel10.Location = new Point(12, 190);
            bunifuLabel10.Name = "bunifuLabel10";
            bunifuLabel10.RightToLeft = RightToLeft.No;
            bunifuLabel10.Size = new Size(55, 21);
            bunifuLabel10.TabIndex = 22;
            bunifuLabel10.Text = "Genero";
            bunifuLabel10.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuDatePicker1
            // 
            bunifuDatePicker1.BackColor = Color.Transparent;
            bunifuDatePicker1.BorderColor = Color.Silver;
            bunifuDatePicker1.BorderRadius = 1;
            bunifuDatePicker1.Color = Color.Silver;
            bunifuDatePicker1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            bunifuDatePicker1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            bunifuDatePicker1.DisabledColor = Color.Gray;
            bunifuDatePicker1.DisplayWeekNumbers = false;
            bunifuDatePicker1.DPHeight = 0;
            bunifuDatePicker1.DropDownAlign = LeftRightAlignment.Right;
            bunifuDatePicker1.FillDatePicker = false;
            bunifuDatePicker1.Font = new Font("Segoe UI", 9F);
            bunifuDatePicker1.ForeColor = Color.Black;
            bunifuDatePicker1.Icon = (Image)resources.GetObject("bunifuDatePicker1.Icon");
            bunifuDatePicker1.IconColor = Color.Gray;
            bunifuDatePicker1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            bunifuDatePicker1.LeftTextMargin = 5;
            bunifuDatePicker1.Location = new Point(185, 217);
            bunifuDatePicker1.MinimumSize = new Size(0, 32);
            bunifuDatePicker1.Name = "bunifuDatePicker1";
            bunifuDatePicker1.Size = new Size(208, 32);
            bunifuDatePicker1.TabIndex = 20;
            // 
            // bunifuLabel9
            // 
            bunifuLabel9.AllowParentOverrides = false;
            bunifuLabel9.AutoEllipsis = false;
            bunifuLabel9.CursorType = Cursors.Default;
            bunifuLabel9.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel9.Location = new Point(185, 190);
            bunifuLabel9.Name = "bunifuLabel9";
            bunifuLabel9.RightToLeft = RightToLeft.No;
            bunifuLabel9.Size = new Size(158, 21);
            bunifuLabel9.TabIndex = 15;
            bunifuLabel9.Text = "Fecha de nacimiento";
            bunifuLabel9.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            bunifuLabel4.AllowParentOverrides = false;
            bunifuLabel4.AutoEllipsis = false;
            bunifuLabel4.CursorType = Cursors.Default;
            bunifuLabel4.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel4.Location = new Point(357, 104);
            bunifuLabel4.Name = "bunifuLabel4";
            bunifuLabel4.RightToLeft = RightToLeft.No;
            bunifuLabel4.Size = new Size(36, 21);
            bunifuLabel4.TabIndex = 13;
            bunifuLabel4.Text = "Curp";
            bunifuLabel4.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox5
            // 
            bunifuTextBox5.AcceptsReturn = false;
            bunifuTextBox5.AcceptsTab = false;
            bunifuTextBox5.AnimationSpeed = 200;
            bunifuTextBox5.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox5.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox5.AutoSizeHeight = true;
            bunifuTextBox5.BackColor = Color.Transparent;
            bunifuTextBox5.BackgroundImage = (Image)resources.GetObject("bunifuTextBox5.BackgroundImage");
            bunifuTextBox5.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox5.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox5.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox5.BorderColorIdle = Color.Silver;
            bunifuTextBox5.BorderRadius = 1;
            bunifuTextBox5.BorderThickness = 1;
            bunifuTextBox5.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox5.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox5.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox5.DefaultText = "";
            bunifuTextBox5.FillColor = Color.White;
            bunifuTextBox5.HideSelection = true;
            bunifuTextBox5.IconLeft = null;
            bunifuTextBox5.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox5.IconPadding = 10;
            bunifuTextBox5.IconRight = null;
            bunifuTextBox5.IconRightCursor = Cursors.IBeam;
            bunifuTextBox5.Location = new Point(357, 131);
            bunifuTextBox5.MaxLength = 32767;
            bunifuTextBox5.MinimumSize = new Size(1, 1);
            bunifuTextBox5.Modified = false;
            bunifuTextBox5.Multiline = false;
            bunifuTextBox5.Name = "bunifuTextBox5";
            stateProperties73.BorderColor = Color.DodgerBlue;
            stateProperties73.FillColor = Color.Empty;
            stateProperties73.ForeColor = Color.Empty;
            stateProperties73.PlaceholderForeColor = Color.Empty;
            bunifuTextBox5.OnActiveState = stateProperties73;
            stateProperties74.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties74.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties74.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties74.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox5.OnDisabledState = stateProperties74;
            stateProperties75.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties75.FillColor = Color.Empty;
            stateProperties75.ForeColor = Color.Empty;
            stateProperties75.PlaceholderForeColor = Color.Empty;
            bunifuTextBox5.OnHoverState = stateProperties75;
            stateProperties76.BorderColor = Color.Silver;
            stateProperties76.FillColor = Color.White;
            stateProperties76.ForeColor = Color.Empty;
            stateProperties76.PlaceholderForeColor = Color.Empty;
            bunifuTextBox5.OnIdleState = stateProperties76;
            bunifuTextBox5.Padding = new Padding(3);
            bunifuTextBox5.PasswordChar = '\0';
            bunifuTextBox5.PlaceholderForeColor = Color.Silver;
            bunifuTextBox5.PlaceholderText = "Enter text";
            bunifuTextBox5.ReadOnly = false;
            bunifuTextBox5.ScrollBars = ScrollBars.None;
            bunifuTextBox5.SelectedText = "";
            bunifuTextBox5.SelectionLength = 0;
            bunifuTextBox5.SelectionStart = 0;
            bunifuTextBox5.ShortcutsEnabled = true;
            bunifuTextBox5.Size = new Size(151, 39);
            bunifuTextBox5.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox5.TabIndex = 12;
            bunifuTextBox5.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox5.TextMarginBottom = 0;
            bunifuTextBox5.TextMarginLeft = 3;
            bunifuTextBox5.TextMarginTop = 1;
            bunifuTextBox5.TextPlaceholder = "Enter text";
            bunifuTextBox5.UseSystemPasswordChar = false;
            bunifuTextBox5.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            bunifuLabel5.AllowParentOverrides = false;
            bunifuLabel5.AutoEllipsis = false;
            bunifuLabel5.CursorType = Cursors.Default;
            bunifuLabel5.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel5.Location = new Point(185, 104);
            bunifuLabel5.Name = "bunifuLabel5";
            bunifuLabel5.RightToLeft = RightToLeft.No;
            bunifuLabel5.Size = new Size(51, 21);
            bunifuLabel5.TabIndex = 11;
            bunifuLabel5.Text = "Correo";
            bunifuLabel5.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox6
            // 
            bunifuTextBox6.AcceptsReturn = false;
            bunifuTextBox6.AcceptsTab = false;
            bunifuTextBox6.AnimationSpeed = 200;
            bunifuTextBox6.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox6.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox6.AutoSizeHeight = true;
            bunifuTextBox6.BackColor = Color.Transparent;
            bunifuTextBox6.BackgroundImage = (Image)resources.GetObject("bunifuTextBox6.BackgroundImage");
            bunifuTextBox6.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox6.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox6.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox6.BorderColorIdle = Color.Silver;
            bunifuTextBox6.BorderRadius = 1;
            bunifuTextBox6.BorderThickness = 1;
            bunifuTextBox6.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox6.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox6.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox6.DefaultText = "";
            bunifuTextBox6.FillColor = Color.White;
            bunifuTextBox6.HideSelection = true;
            bunifuTextBox6.IconLeft = null;
            bunifuTextBox6.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox6.IconPadding = 10;
            bunifuTextBox6.IconRight = null;
            bunifuTextBox6.IconRightCursor = Cursors.IBeam;
            bunifuTextBox6.Location = new Point(185, 131);
            bunifuTextBox6.MaxLength = 32767;
            bunifuTextBox6.MinimumSize = new Size(1, 1);
            bunifuTextBox6.Modified = false;
            bunifuTextBox6.Multiline = false;
            bunifuTextBox6.Name = "bunifuTextBox6";
            stateProperties77.BorderColor = Color.DodgerBlue;
            stateProperties77.FillColor = Color.Empty;
            stateProperties77.ForeColor = Color.Empty;
            stateProperties77.PlaceholderForeColor = Color.Empty;
            bunifuTextBox6.OnActiveState = stateProperties77;
            stateProperties78.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties78.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties78.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties78.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox6.OnDisabledState = stateProperties78;
            stateProperties79.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties79.FillColor = Color.Empty;
            stateProperties79.ForeColor = Color.Empty;
            stateProperties79.PlaceholderForeColor = Color.Empty;
            bunifuTextBox6.OnHoverState = stateProperties79;
            stateProperties80.BorderColor = Color.Silver;
            stateProperties80.FillColor = Color.White;
            stateProperties80.ForeColor = Color.Empty;
            stateProperties80.PlaceholderForeColor = Color.Empty;
            bunifuTextBox6.OnIdleState = stateProperties80;
            bunifuTextBox6.Padding = new Padding(3);
            bunifuTextBox6.PasswordChar = '\0';
            bunifuTextBox6.PlaceholderForeColor = Color.Silver;
            bunifuTextBox6.PlaceholderText = "Enter text";
            bunifuTextBox6.ReadOnly = false;
            bunifuTextBox6.ScrollBars = ScrollBars.None;
            bunifuTextBox6.SelectedText = "";
            bunifuTextBox6.SelectionLength = 0;
            bunifuTextBox6.SelectionStart = 0;
            bunifuTextBox6.ShortcutsEnabled = true;
            bunifuTextBox6.Size = new Size(151, 39);
            bunifuTextBox6.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox6.TabIndex = 10;
            bunifuTextBox6.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox6.TextMarginBottom = 0;
            bunifuTextBox6.TextMarginLeft = 3;
            bunifuTextBox6.TextMarginTop = 1;
            bunifuTextBox6.TextPlaceholder = "Enter text";
            bunifuTextBox6.UseSystemPasswordChar = false;
            bunifuTextBox6.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            bunifuLabel6.AllowParentOverrides = false;
            bunifuLabel6.AutoEllipsis = false;
            bunifuLabel6.CursorType = Cursors.Default;
            bunifuLabel6.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel6.Location = new Point(12, 104);
            bunifuLabel6.Name = "bunifuLabel6";
            bunifuLabel6.RightToLeft = RightToLeft.No;
            bunifuLabel6.Size = new Size(68, 21);
            bunifuLabel6.TabIndex = 9;
            bunifuLabel6.Text = "Telefono";
            bunifuLabel6.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox7
            // 
            bunifuTextBox7.AcceptsReturn = false;
            bunifuTextBox7.AcceptsTab = false;
            bunifuTextBox7.AnimationSpeed = 200;
            bunifuTextBox7.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox7.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox7.AutoSizeHeight = true;
            bunifuTextBox7.BackColor = Color.Transparent;
            bunifuTextBox7.BackgroundImage = (Image)resources.GetObject("bunifuTextBox7.BackgroundImage");
            bunifuTextBox7.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox7.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox7.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox7.BorderColorIdle = Color.Silver;
            bunifuTextBox7.BorderRadius = 1;
            bunifuTextBox7.BorderThickness = 1;
            bunifuTextBox7.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox7.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox7.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox7.DefaultText = "";
            bunifuTextBox7.FillColor = Color.White;
            bunifuTextBox7.HideSelection = true;
            bunifuTextBox7.IconLeft = null;
            bunifuTextBox7.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox7.IconPadding = 10;
            bunifuTextBox7.IconRight = null;
            bunifuTextBox7.IconRightCursor = Cursors.IBeam;
            bunifuTextBox7.Location = new Point(12, 131);
            bunifuTextBox7.MaxLength = 32767;
            bunifuTextBox7.MinimumSize = new Size(1, 1);
            bunifuTextBox7.Modified = false;
            bunifuTextBox7.Multiline = false;
            bunifuTextBox7.Name = "bunifuTextBox7";
            stateProperties81.BorderColor = Color.DodgerBlue;
            stateProperties81.FillColor = Color.Empty;
            stateProperties81.ForeColor = Color.Empty;
            stateProperties81.PlaceholderForeColor = Color.Empty;
            bunifuTextBox7.OnActiveState = stateProperties81;
            stateProperties82.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties82.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties82.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties82.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox7.OnDisabledState = stateProperties82;
            stateProperties83.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties83.FillColor = Color.Empty;
            stateProperties83.ForeColor = Color.Empty;
            stateProperties83.PlaceholderForeColor = Color.Empty;
            bunifuTextBox7.OnHoverState = stateProperties83;
            stateProperties84.BorderColor = Color.Silver;
            stateProperties84.FillColor = Color.White;
            stateProperties84.ForeColor = Color.Empty;
            stateProperties84.PlaceholderForeColor = Color.Empty;
            bunifuTextBox7.OnIdleState = stateProperties84;
            bunifuTextBox7.Padding = new Padding(3);
            bunifuTextBox7.PasswordChar = '\0';
            bunifuTextBox7.PlaceholderForeColor = Color.Silver;
            bunifuTextBox7.PlaceholderText = "Enter text";
            bunifuTextBox7.ReadOnly = false;
            bunifuTextBox7.ScrollBars = ScrollBars.None;
            bunifuTextBox7.SelectedText = "";
            bunifuTextBox7.SelectionLength = 0;
            bunifuTextBox7.SelectionStart = 0;
            bunifuTextBox7.ShortcutsEnabled = true;
            bunifuTextBox7.Size = new Size(151, 39);
            bunifuTextBox7.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox7.TabIndex = 8;
            bunifuTextBox7.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox7.TextMarginBottom = 0;
            bunifuTextBox7.TextMarginLeft = 3;
            bunifuTextBox7.TextMarginTop = 1;
            bunifuTextBox7.TextPlaceholder = "Enter text";
            bunifuTextBox7.UseSystemPasswordChar = false;
            bunifuTextBox7.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            bunifuLabel3.AllowParentOverrides = false;
            bunifuLabel3.AutoEllipsis = false;
            bunifuLabel3.CursorType = Cursors.Default;
            bunifuLabel3.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel3.Location = new Point(357, 19);
            bunifuLabel3.Name = "bunifuLabel3";
            bunifuLabel3.RightToLeft = RightToLeft.No;
            bunifuLabel3.Size = new Size(137, 21);
            bunifuLabel3.TabIndex = 7;
            bunifuLabel3.Text = "Segundo Apellido";
            bunifuLabel3.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox4
            // 
            bunifuTextBox4.AcceptsReturn = false;
            bunifuTextBox4.AcceptsTab = false;
            bunifuTextBox4.AnimationSpeed = 200;
            bunifuTextBox4.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox4.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox4.AutoSizeHeight = true;
            bunifuTextBox4.BackColor = Color.Transparent;
            bunifuTextBox4.BackgroundImage = (Image)resources.GetObject("bunifuTextBox4.BackgroundImage");
            bunifuTextBox4.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox4.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox4.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox4.BorderColorIdle = Color.Silver;
            bunifuTextBox4.BorderRadius = 1;
            bunifuTextBox4.BorderThickness = 1;
            bunifuTextBox4.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox4.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox4.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox4.DefaultText = "";
            bunifuTextBox4.FillColor = Color.White;
            bunifuTextBox4.HideSelection = true;
            bunifuTextBox4.IconLeft = null;
            bunifuTextBox4.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox4.IconPadding = 10;
            bunifuTextBox4.IconRight = null;
            bunifuTextBox4.IconRightCursor = Cursors.IBeam;
            bunifuTextBox4.Location = new Point(357, 46);
            bunifuTextBox4.MaxLength = 32767;
            bunifuTextBox4.MinimumSize = new Size(1, 1);
            bunifuTextBox4.Modified = false;
            bunifuTextBox4.Multiline = false;
            bunifuTextBox4.Name = "bunifuTextBox4";
            stateProperties85.BorderColor = Color.DodgerBlue;
            stateProperties85.FillColor = Color.Empty;
            stateProperties85.ForeColor = Color.Empty;
            stateProperties85.PlaceholderForeColor = Color.Empty;
            bunifuTextBox4.OnActiveState = stateProperties85;
            stateProperties86.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties86.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties86.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties86.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox4.OnDisabledState = stateProperties86;
            stateProperties87.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties87.FillColor = Color.Empty;
            stateProperties87.ForeColor = Color.Empty;
            stateProperties87.PlaceholderForeColor = Color.Empty;
            bunifuTextBox4.OnHoverState = stateProperties87;
            stateProperties88.BorderColor = Color.Silver;
            stateProperties88.FillColor = Color.White;
            stateProperties88.ForeColor = Color.Empty;
            stateProperties88.PlaceholderForeColor = Color.Empty;
            bunifuTextBox4.OnIdleState = stateProperties88;
            bunifuTextBox4.Padding = new Padding(3);
            bunifuTextBox4.PasswordChar = '\0';
            bunifuTextBox4.PlaceholderForeColor = Color.Silver;
            bunifuTextBox4.PlaceholderText = "Enter text";
            bunifuTextBox4.ReadOnly = false;
            bunifuTextBox4.ScrollBars = ScrollBars.None;
            bunifuTextBox4.SelectedText = "";
            bunifuTextBox4.SelectionLength = 0;
            bunifuTextBox4.SelectionStart = 0;
            bunifuTextBox4.ShortcutsEnabled = true;
            bunifuTextBox4.Size = new Size(151, 39);
            bunifuTextBox4.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox4.TabIndex = 6;
            bunifuTextBox4.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox4.TextMarginBottom = 0;
            bunifuTextBox4.TextMarginLeft = 3;
            bunifuTextBox4.TextMarginTop = 1;
            bunifuTextBox4.TextPlaceholder = "Enter text";
            bunifuTextBox4.UseSystemPasswordChar = false;
            bunifuTextBox4.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            bunifuLabel2.AllowParentOverrides = false;
            bunifuLabel2.AutoEllipsis = false;
            bunifuLabel2.CursorType = Cursors.Default;
            bunifuLabel2.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel2.Location = new Point(185, 19);
            bunifuLabel2.Name = "bunifuLabel2";
            bunifuLabel2.RightToLeft = RightToLeft.No;
            bunifuLabel2.Size = new Size(120, 21);
            bunifuLabel2.TabIndex = 5;
            bunifuLabel2.Text = "Primer Apellido";
            bunifuLabel2.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox3
            // 
            bunifuTextBox3.AcceptsReturn = false;
            bunifuTextBox3.AcceptsTab = false;
            bunifuTextBox3.AnimationSpeed = 200;
            bunifuTextBox3.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox3.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox3.AutoSizeHeight = true;
            bunifuTextBox3.BackColor = Color.Transparent;
            bunifuTextBox3.BackgroundImage = (Image)resources.GetObject("bunifuTextBox3.BackgroundImage");
            bunifuTextBox3.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox3.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox3.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox3.BorderColorIdle = Color.Silver;
            bunifuTextBox3.BorderRadius = 1;
            bunifuTextBox3.BorderThickness = 1;
            bunifuTextBox3.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox3.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox3.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox3.DefaultText = "";
            bunifuTextBox3.FillColor = Color.White;
            bunifuTextBox3.HideSelection = true;
            bunifuTextBox3.IconLeft = null;
            bunifuTextBox3.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox3.IconPadding = 10;
            bunifuTextBox3.IconRight = null;
            bunifuTextBox3.IconRightCursor = Cursors.IBeam;
            bunifuTextBox3.Location = new Point(185, 46);
            bunifuTextBox3.MaxLength = 32767;
            bunifuTextBox3.MinimumSize = new Size(1, 1);
            bunifuTextBox3.Modified = false;
            bunifuTextBox3.Multiline = false;
            bunifuTextBox3.Name = "bunifuTextBox3";
            stateProperties89.BorderColor = Color.DodgerBlue;
            stateProperties89.FillColor = Color.Empty;
            stateProperties89.ForeColor = Color.Empty;
            stateProperties89.PlaceholderForeColor = Color.Empty;
            bunifuTextBox3.OnActiveState = stateProperties89;
            stateProperties90.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties90.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties90.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties90.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox3.OnDisabledState = stateProperties90;
            stateProperties91.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties91.FillColor = Color.Empty;
            stateProperties91.ForeColor = Color.Empty;
            stateProperties91.PlaceholderForeColor = Color.Empty;
            bunifuTextBox3.OnHoverState = stateProperties91;
            stateProperties92.BorderColor = Color.Silver;
            stateProperties92.FillColor = Color.White;
            stateProperties92.ForeColor = Color.Empty;
            stateProperties92.PlaceholderForeColor = Color.Empty;
            bunifuTextBox3.OnIdleState = stateProperties92;
            bunifuTextBox3.Padding = new Padding(3);
            bunifuTextBox3.PasswordChar = '\0';
            bunifuTextBox3.PlaceholderForeColor = Color.Silver;
            bunifuTextBox3.PlaceholderText = "Enter text";
            bunifuTextBox3.ReadOnly = false;
            bunifuTextBox3.ScrollBars = ScrollBars.None;
            bunifuTextBox3.SelectedText = "";
            bunifuTextBox3.SelectionLength = 0;
            bunifuTextBox3.SelectionStart = 0;
            bunifuTextBox3.ShortcutsEnabled = true;
            bunifuTextBox3.Size = new Size(151, 39);
            bunifuTextBox3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox3.TabIndex = 4;
            bunifuTextBox3.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox3.TextMarginBottom = 0;
            bunifuTextBox3.TextMarginLeft = 3;
            bunifuTextBox3.TextMarginTop = 1;
            bunifuTextBox3.TextPlaceholder = "Enter text";
            bunifuTextBox3.UseSystemPasswordChar = false;
            bunifuTextBox3.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            bunifuLabel1.AllowParentOverrides = false;
            bunifuLabel1.AutoEllipsis = false;
            bunifuLabel1.CursorType = Cursors.Default;
            bunifuLabel1.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel1.Location = new Point(12, 19);
            bunifuLabel1.Name = "bunifuLabel1";
            bunifuLabel1.RightToLeft = RightToLeft.No;
            bunifuLabel1.Size = new Size(63, 21);
            bunifuLabel1.TabIndex = 3;
            bunifuLabel1.Text = "Nombre";
            bunifuLabel1.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGradientPanel1
            // 
            bunifuGradientPanel1.BackColor = Color.Transparent;
            bunifuGradientPanel1.BackgroundImage = (Image)resources.GetObject("bunifuGradientPanel1.BackgroundImage");
            bunifuGradientPanel1.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuGradientPanel1.BorderRadius = 1;
            bunifuGradientPanel1.GradientBottomLeft = Color.Transparent;
            bunifuGradientPanel1.GradientBottomRight = Color.Transparent;
            bunifuGradientPanel1.GradientTopLeft = Color.Transparent;
            bunifuGradientPanel1.GradientTopRight = Color.Transparent;
            bunifuGradientPanel1.Location = new Point(164, 1018);
            bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            bunifuGradientPanel1.Quality = 10;
            bunifuGradientPanel1.Size = new Size(200, 18);
            bunifuGradientPanel1.TabIndex = 2;
            // 
            // bunifuTextBox1
            // 
            bunifuTextBox1.AcceptsReturn = false;
            bunifuTextBox1.AcceptsTab = false;
            bunifuTextBox1.AnimationSpeed = 200;
            bunifuTextBox1.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox1.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox1.AutoSizeHeight = true;
            bunifuTextBox1.BackColor = Color.Transparent;
            bunifuTextBox1.BackgroundImage = (Image)resources.GetObject("bunifuTextBox1.BackgroundImage");
            bunifuTextBox1.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox1.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox1.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox1.BorderColorIdle = Color.Silver;
            bunifuTextBox1.BorderRadius = 1;
            bunifuTextBox1.BorderThickness = 1;
            bunifuTextBox1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox1.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox1.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox1.DefaultText = "";
            bunifuTextBox1.FillColor = Color.White;
            bunifuTextBox1.HideSelection = true;
            bunifuTextBox1.IconLeft = null;
            bunifuTextBox1.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox1.IconPadding = 10;
            bunifuTextBox1.IconRight = null;
            bunifuTextBox1.IconRightCursor = Cursors.IBeam;
            bunifuTextBox1.Location = new Point(12, 46);
            bunifuTextBox1.MaxLength = 32767;
            bunifuTextBox1.MinimumSize = new Size(1, 1);
            bunifuTextBox1.Modified = false;
            bunifuTextBox1.Multiline = false;
            bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties93.BorderColor = Color.DodgerBlue;
            stateProperties93.FillColor = Color.Empty;
            stateProperties93.ForeColor = Color.Empty;
            stateProperties93.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnActiveState = stateProperties93;
            stateProperties94.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties94.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties94.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties94.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox1.OnDisabledState = stateProperties94;
            stateProperties95.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties95.FillColor = Color.Empty;
            stateProperties95.ForeColor = Color.Empty;
            stateProperties95.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnHoverState = stateProperties95;
            stateProperties96.BorderColor = Color.Silver;
            stateProperties96.FillColor = Color.White;
            stateProperties96.ForeColor = Color.Empty;
            stateProperties96.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnIdleState = stateProperties96;
            bunifuTextBox1.Padding = new Padding(3);
            bunifuTextBox1.PasswordChar = '\0';
            bunifuTextBox1.PlaceholderForeColor = Color.Silver;
            bunifuTextBox1.PlaceholderText = "Enter text";
            bunifuTextBox1.ReadOnly = false;
            bunifuTextBox1.ScrollBars = ScrollBars.None;
            bunifuTextBox1.SelectedText = "";
            bunifuTextBox1.SelectionLength = 0;
            bunifuTextBox1.SelectionStart = 0;
            bunifuTextBox1.ShortcutsEnabled = true;
            bunifuTextBox1.Size = new Size(151, 39);
            bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox1.TabIndex = 0;
            bunifuTextBox1.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox1.TextMarginBottom = 0;
            bunifuTextBox1.TextMarginLeft = 3;
            bunifuTextBox1.TextMarginTop = 1;
            bunifuTextBox1.TextPlaceholder = "Enter text";
            bunifuTextBox1.UseSystemPasswordChar = false;
            bunifuTextBox1.WordWrap = true;
            // 
            // Editar_Paciente
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(583, 534);
            Controls.Add(panel1);
            FormBorderStyle = FormBorderStyle.None;
            Name = "Editar_Paciente";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Editar_Paciente";
            panel1.ResumeLayout(false);
            panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)bunifuDataGridView2).EndInit();
            ((System.ComponentModel.ISupportInitialize)bunifuDataGridView1).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private Panel panel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel12;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox9;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel13;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox10;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel14;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox11;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel15;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox12;
        private PIA_1._0.RJButton rjButton2;
        private PIA_1._0.RJButton rjButton1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private RichTextBox richTextBox1;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView2;
        private DataGridViewTextBoxColumn Alergias;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private DataGridViewTextBoxColumn Enfermedades;
        private ComboBox comboBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Bunifu.UI.WinForms.BunifuDropdown bunifuDropdown1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel16;
    }
}