namespace Pia_2._0
{
    partial class Registrar_Paciente
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Registrar_Paciente));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle4 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle5 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle6 = new DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            panel1 = new Panel();
            bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox8 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel12 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox9 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel13 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox10 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel14 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox11 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel15 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox12 = new Bunifu.UI.WinForms.BunifuTextBox();
            rjButton2 = new PIA_1._0.RJButton();
            rjButton1 = new PIA_1._0.RJButton();
            bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            richTextBox1 = new RichTextBox();
            bunifuDataGridView2 = new Bunifu.UI.WinForms.BunifuDataGridView();
            Alergias = new DataGridViewTextBoxColumn();
            bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            Enfermedades = new DataGridViewTextBoxColumn();
            comboBox1 = new ComboBox();
            bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuDatePicker1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox5 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox6 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox7 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox4 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuTextBox3 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)bunifuDataGridView2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)bunifuDataGridView1).BeginInit();
            SuspendLayout();
            // 
            // panel1
            // 
            panel1.AutoScroll = true;
            panel1.Controls.Add(bunifuLabel8);
            panel1.Controls.Add(bunifuTextBox2);
            panel1.Controls.Add(bunifuLabel11);
            panel1.Controls.Add(bunifuTextBox8);
            panel1.Controls.Add(bunifuLabel12);
            panel1.Controls.Add(bunifuTextBox9);
            panel1.Controls.Add(bunifuLabel13);
            panel1.Controls.Add(bunifuTextBox10);
            panel1.Controls.Add(bunifuLabel14);
            panel1.Controls.Add(bunifuTextBox11);
            panel1.Controls.Add(bunifuLabel15);
            panel1.Controls.Add(bunifuTextBox12);
            panel1.Controls.Add(rjButton2);
            panel1.Controls.Add(rjButton1);
            panel1.Controls.Add(bunifuLabel7);
            panel1.Controls.Add(richTextBox1);
            panel1.Controls.Add(bunifuDataGridView2);
            panel1.Controls.Add(bunifuDataGridView1);
            panel1.Controls.Add(comboBox1);
            panel1.Controls.Add(bunifuLabel10);
            panel1.Controls.Add(bunifuDatePicker1);
            panel1.Controls.Add(bunifuLabel9);
            panel1.Controls.Add(bunifuLabel4);
            panel1.Controls.Add(bunifuTextBox5);
            panel1.Controls.Add(bunifuLabel5);
            panel1.Controls.Add(bunifuTextBox6);
            panel1.Controls.Add(bunifuLabel6);
            panel1.Controls.Add(bunifuTextBox7);
            panel1.Controls.Add(bunifuLabel3);
            panel1.Controls.Add(bunifuTextBox4);
            panel1.Controls.Add(bunifuLabel2);
            panel1.Controls.Add(bunifuTextBox3);
            panel1.Controls.Add(bunifuLabel1);
            panel1.Controls.Add(bunifuGradientPanel1);
            panel1.Controls.Add(bunifuTextBox1);
            panel1.Location = new Point(0, 31);
            panel1.Name = "panel1";
            panel1.Size = new Size(557, 504);
            panel1.TabIndex = 0;
            // 
            // bunifuLabel8
            // 
            bunifuLabel8.AllowParentOverrides = false;
            bunifuLabel8.AutoEllipsis = false;
            bunifuLabel8.CursorType = Cursors.Default;
            bunifuLabel8.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel8.Location = new Point(357, 365);
            bunifuLabel8.Name = "bunifuLabel8";
            bunifuLabel8.RightToLeft = RightToLeft.No;
            bunifuLabel8.Size = new Size(106, 21);
            bunifuLabel8.TabIndex = 40;
            bunifuLabel8.Text = "Codigo Postal";
            bunifuLabel8.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox2
            // 
            bunifuTextBox2.AcceptsReturn = false;
            bunifuTextBox2.AcceptsTab = false;
            bunifuTextBox2.AnimationSpeed = 200;
            bunifuTextBox2.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox2.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox2.AutoSizeHeight = true;
            bunifuTextBox2.BackColor = Color.Transparent;
            bunifuTextBox2.BackgroundImage = (Image)resources.GetObject("bunifuTextBox2.BackgroundImage");
            bunifuTextBox2.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox2.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox2.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox2.BorderColorIdle = Color.Silver;
            bunifuTextBox2.BorderRadius = 1;
            bunifuTextBox2.BorderThickness = 1;
            bunifuTextBox2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox2.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox2.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox2.DefaultText = "";
            bunifuTextBox2.FillColor = Color.White;
            bunifuTextBox2.HideSelection = true;
            bunifuTextBox2.IconLeft = null;
            bunifuTextBox2.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox2.IconPadding = 10;
            bunifuTextBox2.IconRight = null;
            bunifuTextBox2.IconRightCursor = Cursors.IBeam;
            bunifuTextBox2.Location = new Point(357, 392);
            bunifuTextBox2.MaxLength = 32767;
            bunifuTextBox2.MinimumSize = new Size(1, 1);
            bunifuTextBox2.Modified = false;
            bunifuTextBox2.Multiline = false;
            bunifuTextBox2.Name = "bunifuTextBox2";
            stateProperties1.BorderColor = Color.DodgerBlue;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox2.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnIdleState = stateProperties4;
            bunifuTextBox2.Padding = new Padding(3);
            bunifuTextBox2.PasswordChar = '\0';
            bunifuTextBox2.PlaceholderForeColor = Color.Silver;
            bunifuTextBox2.PlaceholderText = "Enter text";
            bunifuTextBox2.ReadOnly = false;
            bunifuTextBox2.ScrollBars = ScrollBars.None;
            bunifuTextBox2.SelectedText = "";
            bunifuTextBox2.SelectionLength = 0;
            bunifuTextBox2.SelectionStart = 0;
            bunifuTextBox2.ShortcutsEnabled = true;
            bunifuTextBox2.Size = new Size(151, 39);
            bunifuTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox2.TabIndex = 39;
            bunifuTextBox2.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox2.TextMarginBottom = 0;
            bunifuTextBox2.TextMarginLeft = 3;
            bunifuTextBox2.TextMarginTop = 1;
            bunifuTextBox2.TextPlaceholder = "Enter text";
            bunifuTextBox2.UseSystemPasswordChar = false;
            bunifuTextBox2.WordWrap = true;
            // 
            // bunifuLabel11
            // 
            bunifuLabel11.AllowParentOverrides = false;
            bunifuLabel11.AutoEllipsis = false;
            bunifuLabel11.CursorType = Cursors.Default;
            bunifuLabel11.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel11.Location = new Point(185, 365);
            bunifuLabel11.Name = "bunifuLabel11";
            bunifuLabel11.RightToLeft = RightToLeft.No;
            bunifuLabel11.Size = new Size(51, 21);
            bunifuLabel11.TabIndex = 38;
            bunifuLabel11.Text = "Estado";
            bunifuLabel11.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox8
            // 
            bunifuTextBox8.AcceptsReturn = false;
            bunifuTextBox8.AcceptsTab = false;
            bunifuTextBox8.AnimationSpeed = 200;
            bunifuTextBox8.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox8.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox8.AutoSizeHeight = true;
            bunifuTextBox8.BackColor = Color.Transparent;
            bunifuTextBox8.BackgroundImage = (Image)resources.GetObject("bunifuTextBox8.BackgroundImage");
            bunifuTextBox8.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox8.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox8.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox8.BorderColorIdle = Color.Silver;
            bunifuTextBox8.BorderRadius = 1;
            bunifuTextBox8.BorderThickness = 1;
            bunifuTextBox8.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox8.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox8.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox8.DefaultText = "";
            bunifuTextBox8.FillColor = Color.White;
            bunifuTextBox8.HideSelection = true;
            bunifuTextBox8.IconLeft = null;
            bunifuTextBox8.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox8.IconPadding = 10;
            bunifuTextBox8.IconRight = null;
            bunifuTextBox8.IconRightCursor = Cursors.IBeam;
            bunifuTextBox8.Location = new Point(185, 392);
            bunifuTextBox8.MaxLength = 32767;
            bunifuTextBox8.MinimumSize = new Size(1, 1);
            bunifuTextBox8.Modified = false;
            bunifuTextBox8.Multiline = false;
            bunifuTextBox8.Name = "bunifuTextBox8";
            stateProperties5.BorderColor = Color.DodgerBlue;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            bunifuTextBox8.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox8.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            bunifuTextBox8.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            bunifuTextBox8.OnIdleState = stateProperties8;
            bunifuTextBox8.Padding = new Padding(3);
            bunifuTextBox8.PasswordChar = '\0';
            bunifuTextBox8.PlaceholderForeColor = Color.Silver;
            bunifuTextBox8.PlaceholderText = "Enter text";
            bunifuTextBox8.ReadOnly = false;
            bunifuTextBox8.ScrollBars = ScrollBars.None;
            bunifuTextBox8.SelectedText = "";
            bunifuTextBox8.SelectionLength = 0;
            bunifuTextBox8.SelectionStart = 0;
            bunifuTextBox8.ShortcutsEnabled = true;
            bunifuTextBox8.Size = new Size(151, 39);
            bunifuTextBox8.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox8.TabIndex = 37;
            bunifuTextBox8.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox8.TextMarginBottom = 0;
            bunifuTextBox8.TextMarginLeft = 3;
            bunifuTextBox8.TextMarginTop = 1;
            bunifuTextBox8.TextPlaceholder = "Enter text";
            bunifuTextBox8.UseSystemPasswordChar = false;
            bunifuTextBox8.WordWrap = true;
            // 
            // bunifuLabel12
            // 
            bunifuLabel12.AllowParentOverrides = false;
            bunifuLabel12.AutoEllipsis = false;
            bunifuLabel12.CursorType = Cursors.Default;
            bunifuLabel12.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel12.Location = new Point(12, 365);
            bunifuLabel12.Name = "bunifuLabel12";
            bunifuLabel12.RightToLeft = RightToLeft.No;
            bunifuLabel12.Size = new Size(54, 21);
            bunifuLabel12.TabIndex = 36;
            bunifuLabel12.Text = "Ciudad";
            bunifuLabel12.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel12.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox9
            // 
            bunifuTextBox9.AcceptsReturn = false;
            bunifuTextBox9.AcceptsTab = false;
            bunifuTextBox9.AnimationSpeed = 200;
            bunifuTextBox9.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox9.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox9.AutoSizeHeight = true;
            bunifuTextBox9.BackColor = Color.Transparent;
            bunifuTextBox9.BackgroundImage = (Image)resources.GetObject("bunifuTextBox9.BackgroundImage");
            bunifuTextBox9.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox9.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox9.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox9.BorderColorIdle = Color.Silver;
            bunifuTextBox9.BorderRadius = 1;
            bunifuTextBox9.BorderThickness = 1;
            bunifuTextBox9.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox9.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox9.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox9.DefaultText = "";
            bunifuTextBox9.FillColor = Color.White;
            bunifuTextBox9.HideSelection = true;
            bunifuTextBox9.IconLeft = null;
            bunifuTextBox9.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox9.IconPadding = 10;
            bunifuTextBox9.IconRight = null;
            bunifuTextBox9.IconRightCursor = Cursors.IBeam;
            bunifuTextBox9.Location = new Point(12, 392);
            bunifuTextBox9.MaxLength = 32767;
            bunifuTextBox9.MinimumSize = new Size(1, 1);
            bunifuTextBox9.Modified = false;
            bunifuTextBox9.Multiline = false;
            bunifuTextBox9.Name = "bunifuTextBox9";
            stateProperties9.BorderColor = Color.DodgerBlue;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            bunifuTextBox9.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox9.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            bunifuTextBox9.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            bunifuTextBox9.OnIdleState = stateProperties12;
            bunifuTextBox9.Padding = new Padding(3);
            bunifuTextBox9.PasswordChar = '\0';
            bunifuTextBox9.PlaceholderForeColor = Color.Silver;
            bunifuTextBox9.PlaceholderText = "Enter text";
            bunifuTextBox9.ReadOnly = false;
            bunifuTextBox9.ScrollBars = ScrollBars.None;
            bunifuTextBox9.SelectedText = "";
            bunifuTextBox9.SelectionLength = 0;
            bunifuTextBox9.SelectionStart = 0;
            bunifuTextBox9.ShortcutsEnabled = true;
            bunifuTextBox9.Size = new Size(151, 39);
            bunifuTextBox9.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox9.TabIndex = 35;
            bunifuTextBox9.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox9.TextMarginBottom = 0;
            bunifuTextBox9.TextMarginLeft = 3;
            bunifuTextBox9.TextMarginTop = 1;
            bunifuTextBox9.TextPlaceholder = "Enter text";
            bunifuTextBox9.UseSystemPasswordChar = false;
            bunifuTextBox9.WordWrap = true;
            // 
            // bunifuLabel13
            // 
            bunifuLabel13.AllowParentOverrides = false;
            bunifuLabel13.AutoEllipsis = false;
            bunifuLabel13.CursorType = Cursors.Default;
            bunifuLabel13.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel13.Location = new Point(357, 280);
            bunifuLabel13.Name = "bunifuLabel13";
            bunifuLabel13.RightToLeft = RightToLeft.No;
            bunifuLabel13.Size = new Size(59, 21);
            bunifuLabel13.TabIndex = 34;
            bunifuLabel13.Text = "Colonia";
            bunifuLabel13.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel13.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox10
            // 
            bunifuTextBox10.AcceptsReturn = false;
            bunifuTextBox10.AcceptsTab = false;
            bunifuTextBox10.AnimationSpeed = 200;
            bunifuTextBox10.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox10.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox10.AutoSizeHeight = true;
            bunifuTextBox10.BackColor = Color.Transparent;
            bunifuTextBox10.BackgroundImage = (Image)resources.GetObject("bunifuTextBox10.BackgroundImage");
            bunifuTextBox10.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox10.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox10.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox10.BorderColorIdle = Color.Silver;
            bunifuTextBox10.BorderRadius = 1;
            bunifuTextBox10.BorderThickness = 1;
            bunifuTextBox10.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox10.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox10.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox10.DefaultText = "";
            bunifuTextBox10.FillColor = Color.White;
            bunifuTextBox10.HideSelection = true;
            bunifuTextBox10.IconLeft = null;
            bunifuTextBox10.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox10.IconPadding = 10;
            bunifuTextBox10.IconRight = null;
            bunifuTextBox10.IconRightCursor = Cursors.IBeam;
            bunifuTextBox10.Location = new Point(357, 307);
            bunifuTextBox10.MaxLength = 32767;
            bunifuTextBox10.MinimumSize = new Size(1, 1);
            bunifuTextBox10.Modified = false;
            bunifuTextBox10.Multiline = false;
            bunifuTextBox10.Name = "bunifuTextBox10";
            stateProperties13.BorderColor = Color.DodgerBlue;
            stateProperties13.FillColor = Color.Empty;
            stateProperties13.ForeColor = Color.Empty;
            stateProperties13.PlaceholderForeColor = Color.Empty;
            bunifuTextBox10.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties14.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox10.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties15.FillColor = Color.Empty;
            stateProperties15.ForeColor = Color.Empty;
            stateProperties15.PlaceholderForeColor = Color.Empty;
            bunifuTextBox10.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = Color.Silver;
            stateProperties16.FillColor = Color.White;
            stateProperties16.ForeColor = Color.Empty;
            stateProperties16.PlaceholderForeColor = Color.Empty;
            bunifuTextBox10.OnIdleState = stateProperties16;
            bunifuTextBox10.Padding = new Padding(3);
            bunifuTextBox10.PasswordChar = '\0';
            bunifuTextBox10.PlaceholderForeColor = Color.Silver;
            bunifuTextBox10.PlaceholderText = "Enter text";
            bunifuTextBox10.ReadOnly = false;
            bunifuTextBox10.ScrollBars = ScrollBars.None;
            bunifuTextBox10.SelectedText = "";
            bunifuTextBox10.SelectionLength = 0;
            bunifuTextBox10.SelectionStart = 0;
            bunifuTextBox10.ShortcutsEnabled = true;
            bunifuTextBox10.Size = new Size(151, 39);
            bunifuTextBox10.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox10.TabIndex = 33;
            bunifuTextBox10.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox10.TextMarginBottom = 0;
            bunifuTextBox10.TextMarginLeft = 3;
            bunifuTextBox10.TextMarginTop = 1;
            bunifuTextBox10.TextPlaceholder = "Enter text";
            bunifuTextBox10.UseSystemPasswordChar = false;
            bunifuTextBox10.WordWrap = true;
            // 
            // bunifuLabel14
            // 
            bunifuLabel14.AllowParentOverrides = false;
            bunifuLabel14.AutoEllipsis = false;
            bunifuLabel14.CursorType = Cursors.Default;
            bunifuLabel14.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel14.Location = new Point(185, 280);
            bunifuLabel14.Name = "bunifuLabel14";
            bunifuLabel14.RightToLeft = RightToLeft.No;
            bunifuLabel14.Size = new Size(63, 21);
            bunifuLabel14.TabIndex = 32;
            bunifuLabel14.Text = "Numero";
            bunifuLabel14.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel14.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox11
            // 
            bunifuTextBox11.AcceptsReturn = false;
            bunifuTextBox11.AcceptsTab = false;
            bunifuTextBox11.AnimationSpeed = 200;
            bunifuTextBox11.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox11.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox11.AutoSizeHeight = true;
            bunifuTextBox11.BackColor = Color.Transparent;
            bunifuTextBox11.BackgroundImage = (Image)resources.GetObject("bunifuTextBox11.BackgroundImage");
            bunifuTextBox11.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox11.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox11.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox11.BorderColorIdle = Color.Silver;
            bunifuTextBox11.BorderRadius = 1;
            bunifuTextBox11.BorderThickness = 1;
            bunifuTextBox11.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox11.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox11.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox11.DefaultText = "";
            bunifuTextBox11.FillColor = Color.White;
            bunifuTextBox11.HideSelection = true;
            bunifuTextBox11.IconLeft = null;
            bunifuTextBox11.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox11.IconPadding = 10;
            bunifuTextBox11.IconRight = null;
            bunifuTextBox11.IconRightCursor = Cursors.IBeam;
            bunifuTextBox11.Location = new Point(185, 307);
            bunifuTextBox11.MaxLength = 32767;
            bunifuTextBox11.MinimumSize = new Size(1, 1);
            bunifuTextBox11.Modified = false;
            bunifuTextBox11.Multiline = false;
            bunifuTextBox11.Name = "bunifuTextBox11";
            stateProperties17.BorderColor = Color.DodgerBlue;
            stateProperties17.FillColor = Color.Empty;
            stateProperties17.ForeColor = Color.Empty;
            stateProperties17.PlaceholderForeColor = Color.Empty;
            bunifuTextBox11.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties18.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties18.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties18.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox11.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties19.FillColor = Color.Empty;
            stateProperties19.ForeColor = Color.Empty;
            stateProperties19.PlaceholderForeColor = Color.Empty;
            bunifuTextBox11.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = Color.Silver;
            stateProperties20.FillColor = Color.White;
            stateProperties20.ForeColor = Color.Empty;
            stateProperties20.PlaceholderForeColor = Color.Empty;
            bunifuTextBox11.OnIdleState = stateProperties20;
            bunifuTextBox11.Padding = new Padding(3);
            bunifuTextBox11.PasswordChar = '\0';
            bunifuTextBox11.PlaceholderForeColor = Color.Silver;
            bunifuTextBox11.PlaceholderText = "Enter text";
            bunifuTextBox11.ReadOnly = false;
            bunifuTextBox11.ScrollBars = ScrollBars.None;
            bunifuTextBox11.SelectedText = "";
            bunifuTextBox11.SelectionLength = 0;
            bunifuTextBox11.SelectionStart = 0;
            bunifuTextBox11.ShortcutsEnabled = true;
            bunifuTextBox11.Size = new Size(151, 39);
            bunifuTextBox11.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox11.TabIndex = 31;
            bunifuTextBox11.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox11.TextMarginBottom = 0;
            bunifuTextBox11.TextMarginLeft = 3;
            bunifuTextBox11.TextMarginTop = 1;
            bunifuTextBox11.TextPlaceholder = "Enter text";
            bunifuTextBox11.UseSystemPasswordChar = false;
            bunifuTextBox11.WordWrap = true;
            bunifuTextBox11.TextChanged += bunifuTextBox11_TextChanged;
            // 
            // bunifuLabel15
            // 
            bunifuLabel15.AllowParentOverrides = false;
            bunifuLabel15.AutoEllipsis = false;
            bunifuLabel15.CursorType = Cursors.Default;
            bunifuLabel15.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel15.Location = new Point(12, 280);
            bunifuLabel15.Name = "bunifuLabel15";
            bunifuLabel15.RightToLeft = RightToLeft.No;
            bunifuLabel15.Size = new Size(38, 21);
            bunifuLabel15.TabIndex = 30;
            bunifuLabel15.Text = "Calle";
            bunifuLabel15.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel15.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox12
            // 
            bunifuTextBox12.AcceptsReturn = false;
            bunifuTextBox12.AcceptsTab = false;
            bunifuTextBox12.AnimationSpeed = 200;
            bunifuTextBox12.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox12.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox12.AutoSizeHeight = true;
            bunifuTextBox12.BackColor = Color.Transparent;
            bunifuTextBox12.BackgroundImage = (Image)resources.GetObject("bunifuTextBox12.BackgroundImage");
            bunifuTextBox12.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox12.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox12.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox12.BorderColorIdle = Color.Silver;
            bunifuTextBox12.BorderRadius = 1;
            bunifuTextBox12.BorderThickness = 1;
            bunifuTextBox12.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox12.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox12.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox12.DefaultText = "";
            bunifuTextBox12.FillColor = Color.White;
            bunifuTextBox12.HideSelection = true;
            bunifuTextBox12.IconLeft = null;
            bunifuTextBox12.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox12.IconPadding = 10;
            bunifuTextBox12.IconRight = null;
            bunifuTextBox12.IconRightCursor = Cursors.IBeam;
            bunifuTextBox12.Location = new Point(12, 307);
            bunifuTextBox12.MaxLength = 32767;
            bunifuTextBox12.MinimumSize = new Size(1, 1);
            bunifuTextBox12.Modified = false;
            bunifuTextBox12.Multiline = false;
            bunifuTextBox12.Name = "bunifuTextBox12";
            stateProperties21.BorderColor = Color.DodgerBlue;
            stateProperties21.FillColor = Color.Empty;
            stateProperties21.ForeColor = Color.Empty;
            stateProperties21.PlaceholderForeColor = Color.Empty;
            bunifuTextBox12.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties22.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties22.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties22.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox12.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties23.FillColor = Color.Empty;
            stateProperties23.ForeColor = Color.Empty;
            stateProperties23.PlaceholderForeColor = Color.Empty;
            bunifuTextBox12.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = Color.Silver;
            stateProperties24.FillColor = Color.White;
            stateProperties24.ForeColor = Color.Empty;
            stateProperties24.PlaceholderForeColor = Color.Empty;
            bunifuTextBox12.OnIdleState = stateProperties24;
            bunifuTextBox12.Padding = new Padding(3);
            bunifuTextBox12.PasswordChar = '\0';
            bunifuTextBox12.PlaceholderForeColor = Color.Silver;
            bunifuTextBox12.PlaceholderText = "Enter text";
            bunifuTextBox12.ReadOnly = false;
            bunifuTextBox12.ScrollBars = ScrollBars.None;
            bunifuTextBox12.SelectedText = "";
            bunifuTextBox12.SelectionLength = 0;
            bunifuTextBox12.SelectionStart = 0;
            bunifuTextBox12.ShortcutsEnabled = true;
            bunifuTextBox12.Size = new Size(151, 39);
            bunifuTextBox12.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox12.TabIndex = 29;
            bunifuTextBox12.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox12.TextMarginBottom = 0;
            bunifuTextBox12.TextMarginLeft = 3;
            bunifuTextBox12.TextMarginTop = 1;
            bunifuTextBox12.TextPlaceholder = "Enter text";
            bunifuTextBox12.UseSystemPasswordChar = false;
            bunifuTextBox12.WordWrap = true;
            // 
            // rjButton2
            // 
            rjButton2.BackColor = Color.Gray;
            rjButton2.BackgroundColor = Color.Gray;
            rjButton2.BorderColor = Color.PaleVioletRed;
            rjButton2.BorderRadius = 15;
            rjButton2.BorderSize = 0;
            rjButton2.FlatAppearance.BorderSize = 0;
            rjButton2.FlatStyle = FlatStyle.Flat;
            rjButton2.Font = new Font("Segoe UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            rjButton2.ForeColor = Color.White;
            rjButton2.Location = new Point(214, 943);
            rjButton2.Name = "rjButton2";
            rjButton2.Size = new Size(150, 40);
            rjButton2.TabIndex = 28;
            rjButton2.Text = "Cancelar";
            rjButton2.TextColor = Color.White;
            rjButton2.UseVisualStyleBackColor = false;
            rjButton2.Click += rjButton2_Click;
            // 
            // rjButton1
            // 
            rjButton1.BackColor = Color.RoyalBlue;
            rjButton1.BackgroundColor = Color.RoyalBlue;
            rjButton1.BorderColor = Color.PaleVioletRed;
            rjButton1.BorderRadius = 15;
            rjButton1.BorderSize = 0;
            rjButton1.FlatAppearance.BorderSize = 0;
            rjButton1.FlatStyle = FlatStyle.Flat;
            rjButton1.Font = new Font("Segoe UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            rjButton1.ForeColor = Color.White;
            rjButton1.Location = new Point(370, 943);
            rjButton1.Name = "rjButton1";
            rjButton1.Size = new Size(150, 40);
            rjButton1.TabIndex = 0;
            rjButton1.Text = "Agregar";
            rjButton1.TextColor = Color.White;
            rjButton1.UseVisualStyleBackColor = false;
            rjButton1.Click += rjButton1_Click;
            // 
            // bunifuLabel7
            // 
            bunifuLabel7.AllowParentOverrides = false;
            bunifuLabel7.AutoEllipsis = false;
            bunifuLabel7.CursorType = Cursors.Default;
            bunifuLabel7.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel7.Location = new Point(12, 679);
            bunifuLabel7.Name = "bunifuLabel7";
            bunifuLabel7.RightToLeft = RightToLeft.No;
            bunifuLabel7.Size = new Size(111, 21);
            bunifuLabel7.TabIndex = 27;
            bunifuLabel7.Text = "Observaciones";
            bunifuLabel7.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // richTextBox1
            // 
            richTextBox1.Location = new Point(12, 706);
            richTextBox1.Name = "richTextBox1";
            richTextBox1.Size = new Size(381, 208);
            richTextBox1.TabIndex = 26;
            richTextBox1.Text = "";
            // 
            // bunifuDataGridView2
            // 
            bunifuDataGridView2.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle1.ForeColor = Color.Black;
            bunifuDataGridView2.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            bunifuDataGridView2.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            bunifuDataGridView2.BorderStyle = BorderStyle.None;
            bunifuDataGridView2.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            bunifuDataGridView2.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = Color.White;
            dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle2.SelectionForeColor = Color.White;
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            bunifuDataGridView2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            bunifuDataGridView2.ColumnHeadersHeight = 40;
            bunifuDataGridView2.Columns.AddRange(new DataGridViewColumn[] { Alergias });
            bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            bunifuDataGridView2.CurrentTheme.BackColor = Color.White;
            bunifuDataGridView2.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            bunifuDataGridView2.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            bunifuDataGridView2.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            bunifuDataGridView2.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            bunifuDataGridView2.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            bunifuDataGridView2.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            bunifuDataGridView2.CurrentTheme.Name = null;
            bunifuDataGridView2.CurrentTheme.RowsStyle.BackColor = Color.White;
            bunifuDataGridView2.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            bunifuDataGridView2.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            bunifuDataGridView2.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            bunifuDataGridView2.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.White;
            dataGridViewCellStyle3.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle3.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            bunifuDataGridView2.DefaultCellStyle = dataGridViewCellStyle3;
            bunifuDataGridView2.EnableHeadersVisualStyles = false;
            bunifuDataGridView2.GridColor = Color.FromArgb(221, 238, 255);
            bunifuDataGridView2.HeaderBackColor = Color.DodgerBlue;
            bunifuDataGridView2.HeaderBgColor = Color.Empty;
            bunifuDataGridView2.HeaderForeColor = Color.White;
            bunifuDataGridView2.Location = new Point(293, 499);
            bunifuDataGridView2.Name = "bunifuDataGridView2";
            bunifuDataGridView2.RowHeadersVisible = false;
            bunifuDataGridView2.RowTemplate.Height = 40;
            bunifuDataGridView2.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            bunifuDataGridView2.Size = new Size(227, 150);
            bunifuDataGridView2.TabIndex = 25;
            bunifuDataGridView2.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // Alergias
            // 
            Alergias.HeaderText = "Alergias";
            Alergias.Name = "Alergias";
            // 
            // bunifuDataGridView1
            // 
            bunifuDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle4.ForeColor = Color.Black;
            bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            bunifuDataGridView1.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            bunifuDataGridView1.BorderStyle = BorderStyle.None;
            bunifuDataGridView1.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            bunifuDataGridView1.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = Color.White;
            dataGridViewCellStyle5.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle5.SelectionForeColor = Color.White;
            dataGridViewCellStyle5.WrapMode = DataGridViewTriState.True;
            bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            bunifuDataGridView1.ColumnHeadersHeight = 40;
            bunifuDataGridView1.Columns.AddRange(new DataGridViewColumn[] { Enfermedades });
            bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            bunifuDataGridView1.CurrentTheme.BackColor = Color.White;
            bunifuDataGridView1.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            bunifuDataGridView1.CurrentTheme.Name = null;
            bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = Color.White;
            bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle6.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = Color.White;
            dataGridViewCellStyle6.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle6.SelectionForeColor = Color.Black;
            dataGridViewCellStyle6.WrapMode = DataGridViewTriState.False;
            bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle6;
            bunifuDataGridView1.EnableHeadersVisualStyles = false;
            bunifuDataGridView1.GridColor = Color.FromArgb(221, 238, 255);
            bunifuDataGridView1.HeaderBackColor = Color.DodgerBlue;
            bunifuDataGridView1.HeaderBgColor = Color.Empty;
            bunifuDataGridView1.HeaderForeColor = Color.White;
            bunifuDataGridView1.Location = new Point(12, 499);
            bunifuDataGridView1.Name = "bunifuDataGridView1";
            bunifuDataGridView1.RowHeadersVisible = false;
            bunifuDataGridView1.RowTemplate.Height = 40;
            bunifuDataGridView1.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            bunifuDataGridView1.Size = new Size(227, 150);
            bunifuDataGridView1.TabIndex = 24;
            bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // Enfermedades
            // 
            Enfermedades.HeaderText = "Enfermedades";
            Enfermedades.Name = "Enfermedades";
            // 
            // comboBox1
            // 
            comboBox1.FormattingEnabled = true;
            comboBox1.Items.AddRange(new object[] { "Masculino", "Femenino" });
            comboBox1.Location = new Point(12, 217);
            comboBox1.Name = "comboBox1";
            comboBox1.Size = new Size(151, 23);
            comboBox1.TabIndex = 23;
            // 
            // bunifuLabel10
            // 
            bunifuLabel10.AllowParentOverrides = false;
            bunifuLabel10.AutoEllipsis = false;
            bunifuLabel10.CursorType = Cursors.Default;
            bunifuLabel10.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel10.Location = new Point(12, 190);
            bunifuLabel10.Name = "bunifuLabel10";
            bunifuLabel10.RightToLeft = RightToLeft.No;
            bunifuLabel10.Size = new Size(55, 21);
            bunifuLabel10.TabIndex = 22;
            bunifuLabel10.Text = "Genero";
            bunifuLabel10.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuDatePicker1
            // 
            bunifuDatePicker1.BackColor = Color.Transparent;
            bunifuDatePicker1.BorderColor = Color.Silver;
            bunifuDatePicker1.BorderRadius = 1;
            bunifuDatePicker1.Color = Color.Silver;
            bunifuDatePicker1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            bunifuDatePicker1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            bunifuDatePicker1.DisabledColor = Color.Gray;
            bunifuDatePicker1.DisplayWeekNumbers = false;
            bunifuDatePicker1.DPHeight = 0;
            bunifuDatePicker1.DropDownAlign = LeftRightAlignment.Right;
            bunifuDatePicker1.FillDatePicker = false;
            bunifuDatePicker1.Font = new Font("Segoe UI", 9F);
            bunifuDatePicker1.ForeColor = Color.Black;
            bunifuDatePicker1.Icon = (Image)resources.GetObject("bunifuDatePicker1.Icon");
            bunifuDatePicker1.IconColor = Color.Gray;
            bunifuDatePicker1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            bunifuDatePicker1.LeftTextMargin = 5;
            bunifuDatePicker1.Location = new Point(185, 217);
            bunifuDatePicker1.MinimumSize = new Size(0, 32);
            bunifuDatePicker1.Name = "bunifuDatePicker1";
            bunifuDatePicker1.Size = new Size(208, 32);
            bunifuDatePicker1.TabIndex = 20;
            // 
            // bunifuLabel9
            // 
            bunifuLabel9.AllowParentOverrides = false;
            bunifuLabel9.AutoEllipsis = false;
            bunifuLabel9.CursorType = Cursors.Default;
            bunifuLabel9.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel9.Location = new Point(185, 190);
            bunifuLabel9.Name = "bunifuLabel9";
            bunifuLabel9.RightToLeft = RightToLeft.No;
            bunifuLabel9.Size = new Size(158, 21);
            bunifuLabel9.TabIndex = 15;
            bunifuLabel9.Text = "Fecha de nacimiento";
            bunifuLabel9.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            bunifuLabel9.Click += bunifuLabel9_Click;
            // 
            // bunifuLabel4
            // 
            bunifuLabel4.AllowParentOverrides = false;
            bunifuLabel4.AutoEllipsis = false;
            bunifuLabel4.CursorType = Cursors.Default;
            bunifuLabel4.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel4.Location = new Point(357, 104);
            bunifuLabel4.Name = "bunifuLabel4";
            bunifuLabel4.RightToLeft = RightToLeft.No;
            bunifuLabel4.Size = new Size(36, 21);
            bunifuLabel4.TabIndex = 13;
            bunifuLabel4.Text = "Curp";
            bunifuLabel4.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox5
            // 
            bunifuTextBox5.AcceptsReturn = false;
            bunifuTextBox5.AcceptsTab = false;
            bunifuTextBox5.AnimationSpeed = 200;
            bunifuTextBox5.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox5.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox5.AutoSizeHeight = true;
            bunifuTextBox5.BackColor = Color.Transparent;
            bunifuTextBox5.BackgroundImage = (Image)resources.GetObject("bunifuTextBox5.BackgroundImage");
            bunifuTextBox5.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox5.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox5.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox5.BorderColorIdle = Color.Silver;
            bunifuTextBox5.BorderRadius = 1;
            bunifuTextBox5.BorderThickness = 1;
            bunifuTextBox5.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox5.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox5.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox5.DefaultText = "";
            bunifuTextBox5.FillColor = Color.White;
            bunifuTextBox5.HideSelection = true;
            bunifuTextBox5.IconLeft = null;
            bunifuTextBox5.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox5.IconPadding = 10;
            bunifuTextBox5.IconRight = null;
            bunifuTextBox5.IconRightCursor = Cursors.IBeam;
            bunifuTextBox5.Location = new Point(357, 131);
            bunifuTextBox5.MaxLength = 32767;
            bunifuTextBox5.MinimumSize = new Size(1, 1);
            bunifuTextBox5.Modified = false;
            bunifuTextBox5.Multiline = false;
            bunifuTextBox5.Name = "bunifuTextBox5";
            stateProperties25.BorderColor = Color.DodgerBlue;
            stateProperties25.FillColor = Color.Empty;
            stateProperties25.ForeColor = Color.Empty;
            stateProperties25.PlaceholderForeColor = Color.Empty;
            bunifuTextBox5.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties26.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties26.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties26.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox5.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties27.FillColor = Color.Empty;
            stateProperties27.ForeColor = Color.Empty;
            stateProperties27.PlaceholderForeColor = Color.Empty;
            bunifuTextBox5.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = Color.Silver;
            stateProperties28.FillColor = Color.White;
            stateProperties28.ForeColor = Color.Empty;
            stateProperties28.PlaceholderForeColor = Color.Empty;
            bunifuTextBox5.OnIdleState = stateProperties28;
            bunifuTextBox5.Padding = new Padding(3);
            bunifuTextBox5.PasswordChar = '\0';
            bunifuTextBox5.PlaceholderForeColor = Color.Silver;
            bunifuTextBox5.PlaceholderText = "Enter text";
            bunifuTextBox5.ReadOnly = false;
            bunifuTextBox5.ScrollBars = ScrollBars.None;
            bunifuTextBox5.SelectedText = "";
            bunifuTextBox5.SelectionLength = 0;
            bunifuTextBox5.SelectionStart = 0;
            bunifuTextBox5.ShortcutsEnabled = true;
            bunifuTextBox5.Size = new Size(151, 39);
            bunifuTextBox5.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox5.TabIndex = 12;
            bunifuTextBox5.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox5.TextMarginBottom = 0;
            bunifuTextBox5.TextMarginLeft = 3;
            bunifuTextBox5.TextMarginTop = 1;
            bunifuTextBox5.TextPlaceholder = "Enter text";
            bunifuTextBox5.UseSystemPasswordChar = false;
            bunifuTextBox5.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            bunifuLabel5.AllowParentOverrides = false;
            bunifuLabel5.AutoEllipsis = false;
            bunifuLabel5.CursorType = Cursors.Default;
            bunifuLabel5.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel5.Location = new Point(185, 104);
            bunifuLabel5.Name = "bunifuLabel5";
            bunifuLabel5.RightToLeft = RightToLeft.No;
            bunifuLabel5.Size = new Size(51, 21);
            bunifuLabel5.TabIndex = 11;
            bunifuLabel5.Text = "Correo";
            bunifuLabel5.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox6
            // 
            bunifuTextBox6.AcceptsReturn = false;
            bunifuTextBox6.AcceptsTab = false;
            bunifuTextBox6.AnimationSpeed = 200;
            bunifuTextBox6.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox6.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox6.AutoSizeHeight = true;
            bunifuTextBox6.BackColor = Color.Transparent;
            bunifuTextBox6.BackgroundImage = (Image)resources.GetObject("bunifuTextBox6.BackgroundImage");
            bunifuTextBox6.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox6.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox6.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox6.BorderColorIdle = Color.Silver;
            bunifuTextBox6.BorderRadius = 1;
            bunifuTextBox6.BorderThickness = 1;
            bunifuTextBox6.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox6.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox6.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox6.DefaultText = "";
            bunifuTextBox6.FillColor = Color.White;
            bunifuTextBox6.HideSelection = true;
            bunifuTextBox6.IconLeft = null;
            bunifuTextBox6.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox6.IconPadding = 10;
            bunifuTextBox6.IconRight = null;
            bunifuTextBox6.IconRightCursor = Cursors.IBeam;
            bunifuTextBox6.Location = new Point(185, 131);
            bunifuTextBox6.MaxLength = 32767;
            bunifuTextBox6.MinimumSize = new Size(1, 1);
            bunifuTextBox6.Modified = false;
            bunifuTextBox6.Multiline = false;
            bunifuTextBox6.Name = "bunifuTextBox6";
            stateProperties29.BorderColor = Color.DodgerBlue;
            stateProperties29.FillColor = Color.Empty;
            stateProperties29.ForeColor = Color.Empty;
            stateProperties29.PlaceholderForeColor = Color.Empty;
            bunifuTextBox6.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties30.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties30.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties30.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox6.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties31.FillColor = Color.Empty;
            stateProperties31.ForeColor = Color.Empty;
            stateProperties31.PlaceholderForeColor = Color.Empty;
            bunifuTextBox6.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = Color.Silver;
            stateProperties32.FillColor = Color.White;
            stateProperties32.ForeColor = Color.Empty;
            stateProperties32.PlaceholderForeColor = Color.Empty;
            bunifuTextBox6.OnIdleState = stateProperties32;
            bunifuTextBox6.Padding = new Padding(3);
            bunifuTextBox6.PasswordChar = '\0';
            bunifuTextBox6.PlaceholderForeColor = Color.Silver;
            bunifuTextBox6.PlaceholderText = "Enter text";
            bunifuTextBox6.ReadOnly = false;
            bunifuTextBox6.ScrollBars = ScrollBars.None;
            bunifuTextBox6.SelectedText = "";
            bunifuTextBox6.SelectionLength = 0;
            bunifuTextBox6.SelectionStart = 0;
            bunifuTextBox6.ShortcutsEnabled = true;
            bunifuTextBox6.Size = new Size(151, 39);
            bunifuTextBox6.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox6.TabIndex = 10;
            bunifuTextBox6.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox6.TextMarginBottom = 0;
            bunifuTextBox6.TextMarginLeft = 3;
            bunifuTextBox6.TextMarginTop = 1;
            bunifuTextBox6.TextPlaceholder = "Enter text";
            bunifuTextBox6.UseSystemPasswordChar = false;
            bunifuTextBox6.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            bunifuLabel6.AllowParentOverrides = false;
            bunifuLabel6.AutoEllipsis = false;
            bunifuLabel6.CursorType = Cursors.Default;
            bunifuLabel6.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel6.Location = new Point(12, 104);
            bunifuLabel6.Name = "bunifuLabel6";
            bunifuLabel6.RightToLeft = RightToLeft.No;
            bunifuLabel6.Size = new Size(68, 21);
            bunifuLabel6.TabIndex = 9;
            bunifuLabel6.Text = "Telefono";
            bunifuLabel6.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox7
            // 
            bunifuTextBox7.AcceptsReturn = false;
            bunifuTextBox7.AcceptsTab = false;
            bunifuTextBox7.AnimationSpeed = 200;
            bunifuTextBox7.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox7.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox7.AutoSizeHeight = true;
            bunifuTextBox7.BackColor = Color.Transparent;
            bunifuTextBox7.BackgroundImage = (Image)resources.GetObject("bunifuTextBox7.BackgroundImage");
            bunifuTextBox7.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox7.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox7.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox7.BorderColorIdle = Color.Silver;
            bunifuTextBox7.BorderRadius = 1;
            bunifuTextBox7.BorderThickness = 1;
            bunifuTextBox7.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox7.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox7.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox7.DefaultText = "";
            bunifuTextBox7.FillColor = Color.White;
            bunifuTextBox7.HideSelection = true;
            bunifuTextBox7.IconLeft = null;
            bunifuTextBox7.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox7.IconPadding = 10;
            bunifuTextBox7.IconRight = null;
            bunifuTextBox7.IconRightCursor = Cursors.IBeam;
            bunifuTextBox7.Location = new Point(12, 131);
            bunifuTextBox7.MaxLength = 32767;
            bunifuTextBox7.MinimumSize = new Size(1, 1);
            bunifuTextBox7.Modified = false;
            bunifuTextBox7.Multiline = false;
            bunifuTextBox7.Name = "bunifuTextBox7";
            stateProperties33.BorderColor = Color.DodgerBlue;
            stateProperties33.FillColor = Color.Empty;
            stateProperties33.ForeColor = Color.Empty;
            stateProperties33.PlaceholderForeColor = Color.Empty;
            bunifuTextBox7.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties34.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties34.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties34.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox7.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties35.FillColor = Color.Empty;
            stateProperties35.ForeColor = Color.Empty;
            stateProperties35.PlaceholderForeColor = Color.Empty;
            bunifuTextBox7.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = Color.Silver;
            stateProperties36.FillColor = Color.White;
            stateProperties36.ForeColor = Color.Empty;
            stateProperties36.PlaceholderForeColor = Color.Empty;
            bunifuTextBox7.OnIdleState = stateProperties36;
            bunifuTextBox7.Padding = new Padding(3);
            bunifuTextBox7.PasswordChar = '\0';
            bunifuTextBox7.PlaceholderForeColor = Color.Silver;
            bunifuTextBox7.PlaceholderText = "Enter text";
            bunifuTextBox7.ReadOnly = false;
            bunifuTextBox7.ScrollBars = ScrollBars.None;
            bunifuTextBox7.SelectedText = "";
            bunifuTextBox7.SelectionLength = 0;
            bunifuTextBox7.SelectionStart = 0;
            bunifuTextBox7.ShortcutsEnabled = true;
            bunifuTextBox7.Size = new Size(151, 39);
            bunifuTextBox7.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox7.TabIndex = 8;
            bunifuTextBox7.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox7.TextMarginBottom = 0;
            bunifuTextBox7.TextMarginLeft = 3;
            bunifuTextBox7.TextMarginTop = 1;
            bunifuTextBox7.TextPlaceholder = "Enter text";
            bunifuTextBox7.UseSystemPasswordChar = false;
            bunifuTextBox7.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            bunifuLabel3.AllowParentOverrides = false;
            bunifuLabel3.AutoEllipsis = false;
            bunifuLabel3.CursorType = Cursors.Default;
            bunifuLabel3.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel3.Location = new Point(357, 19);
            bunifuLabel3.Name = "bunifuLabel3";
            bunifuLabel3.RightToLeft = RightToLeft.No;
            bunifuLabel3.Size = new Size(137, 21);
            bunifuLabel3.TabIndex = 7;
            bunifuLabel3.Text = "Segundo Apellido";
            bunifuLabel3.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox4
            // 
            bunifuTextBox4.AcceptsReturn = false;
            bunifuTextBox4.AcceptsTab = false;
            bunifuTextBox4.AnimationSpeed = 200;
            bunifuTextBox4.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox4.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox4.AutoSizeHeight = true;
            bunifuTextBox4.BackColor = Color.Transparent;
            bunifuTextBox4.BackgroundImage = (Image)resources.GetObject("bunifuTextBox4.BackgroundImage");
            bunifuTextBox4.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox4.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox4.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox4.BorderColorIdle = Color.Silver;
            bunifuTextBox4.BorderRadius = 1;
            bunifuTextBox4.BorderThickness = 1;
            bunifuTextBox4.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox4.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox4.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox4.DefaultText = "";
            bunifuTextBox4.FillColor = Color.White;
            bunifuTextBox4.HideSelection = true;
            bunifuTextBox4.IconLeft = null;
            bunifuTextBox4.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox4.IconPadding = 10;
            bunifuTextBox4.IconRight = null;
            bunifuTextBox4.IconRightCursor = Cursors.IBeam;
            bunifuTextBox4.Location = new Point(357, 46);
            bunifuTextBox4.MaxLength = 32767;
            bunifuTextBox4.MinimumSize = new Size(1, 1);
            bunifuTextBox4.Modified = false;
            bunifuTextBox4.Multiline = false;
            bunifuTextBox4.Name = "bunifuTextBox4";
            stateProperties37.BorderColor = Color.DodgerBlue;
            stateProperties37.FillColor = Color.Empty;
            stateProperties37.ForeColor = Color.Empty;
            stateProperties37.PlaceholderForeColor = Color.Empty;
            bunifuTextBox4.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties38.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties38.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties38.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox4.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties39.FillColor = Color.Empty;
            stateProperties39.ForeColor = Color.Empty;
            stateProperties39.PlaceholderForeColor = Color.Empty;
            bunifuTextBox4.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = Color.Silver;
            stateProperties40.FillColor = Color.White;
            stateProperties40.ForeColor = Color.Empty;
            stateProperties40.PlaceholderForeColor = Color.Empty;
            bunifuTextBox4.OnIdleState = stateProperties40;
            bunifuTextBox4.Padding = new Padding(3);
            bunifuTextBox4.PasswordChar = '\0';
            bunifuTextBox4.PlaceholderForeColor = Color.Silver;
            bunifuTextBox4.PlaceholderText = "Enter text";
            bunifuTextBox4.ReadOnly = false;
            bunifuTextBox4.ScrollBars = ScrollBars.None;
            bunifuTextBox4.SelectedText = "";
            bunifuTextBox4.SelectionLength = 0;
            bunifuTextBox4.SelectionStart = 0;
            bunifuTextBox4.ShortcutsEnabled = true;
            bunifuTextBox4.Size = new Size(151, 39);
            bunifuTextBox4.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox4.TabIndex = 6;
            bunifuTextBox4.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox4.TextMarginBottom = 0;
            bunifuTextBox4.TextMarginLeft = 3;
            bunifuTextBox4.TextMarginTop = 1;
            bunifuTextBox4.TextPlaceholder = "Enter text";
            bunifuTextBox4.UseSystemPasswordChar = false;
            bunifuTextBox4.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            bunifuLabel2.AllowParentOverrides = false;
            bunifuLabel2.AutoEllipsis = false;
            bunifuLabel2.CursorType = Cursors.Default;
            bunifuLabel2.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel2.Location = new Point(185, 19);
            bunifuLabel2.Name = "bunifuLabel2";
            bunifuLabel2.RightToLeft = RightToLeft.No;
            bunifuLabel2.Size = new Size(120, 21);
            bunifuLabel2.TabIndex = 5;
            bunifuLabel2.Text = "Primer Apellido";
            bunifuLabel2.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            bunifuLabel2.Click += bunifuLabel2_Click;
            // 
            // bunifuTextBox3
            // 
            bunifuTextBox3.AcceptsReturn = false;
            bunifuTextBox3.AcceptsTab = false;
            bunifuTextBox3.AnimationSpeed = 200;
            bunifuTextBox3.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox3.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox3.AutoSizeHeight = true;
            bunifuTextBox3.BackColor = Color.Transparent;
            bunifuTextBox3.BackgroundImage = (Image)resources.GetObject("bunifuTextBox3.BackgroundImage");
            bunifuTextBox3.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox3.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox3.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox3.BorderColorIdle = Color.Silver;
            bunifuTextBox3.BorderRadius = 1;
            bunifuTextBox3.BorderThickness = 1;
            bunifuTextBox3.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox3.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox3.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox3.DefaultText = "";
            bunifuTextBox3.FillColor = Color.White;
            bunifuTextBox3.HideSelection = true;
            bunifuTextBox3.IconLeft = null;
            bunifuTextBox3.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox3.IconPadding = 10;
            bunifuTextBox3.IconRight = null;
            bunifuTextBox3.IconRightCursor = Cursors.IBeam;
            bunifuTextBox3.Location = new Point(185, 46);
            bunifuTextBox3.MaxLength = 32767;
            bunifuTextBox3.MinimumSize = new Size(1, 1);
            bunifuTextBox3.Modified = false;
            bunifuTextBox3.Multiline = false;
            bunifuTextBox3.Name = "bunifuTextBox3";
            stateProperties41.BorderColor = Color.DodgerBlue;
            stateProperties41.FillColor = Color.Empty;
            stateProperties41.ForeColor = Color.Empty;
            stateProperties41.PlaceholderForeColor = Color.Empty;
            bunifuTextBox3.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties42.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties42.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties42.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox3.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties43.FillColor = Color.Empty;
            stateProperties43.ForeColor = Color.Empty;
            stateProperties43.PlaceholderForeColor = Color.Empty;
            bunifuTextBox3.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = Color.Silver;
            stateProperties44.FillColor = Color.White;
            stateProperties44.ForeColor = Color.Empty;
            stateProperties44.PlaceholderForeColor = Color.Empty;
            bunifuTextBox3.OnIdleState = stateProperties44;
            bunifuTextBox3.Padding = new Padding(3);
            bunifuTextBox3.PasswordChar = '\0';
            bunifuTextBox3.PlaceholderForeColor = Color.Silver;
            bunifuTextBox3.PlaceholderText = "Enter text";
            bunifuTextBox3.ReadOnly = false;
            bunifuTextBox3.ScrollBars = ScrollBars.None;
            bunifuTextBox3.SelectedText = "";
            bunifuTextBox3.SelectionLength = 0;
            bunifuTextBox3.SelectionStart = 0;
            bunifuTextBox3.ShortcutsEnabled = true;
            bunifuTextBox3.Size = new Size(151, 39);
            bunifuTextBox3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox3.TabIndex = 4;
            bunifuTextBox3.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox3.TextMarginBottom = 0;
            bunifuTextBox3.TextMarginLeft = 3;
            bunifuTextBox3.TextMarginTop = 1;
            bunifuTextBox3.TextPlaceholder = "Enter text";
            bunifuTextBox3.UseSystemPasswordChar = false;
            bunifuTextBox3.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            bunifuLabel1.AllowParentOverrides = false;
            bunifuLabel1.AutoEllipsis = false;
            bunifuLabel1.CursorType = Cursors.Default;
            bunifuLabel1.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel1.Location = new Point(12, 19);
            bunifuLabel1.Name = "bunifuLabel1";
            bunifuLabel1.RightToLeft = RightToLeft.No;
            bunifuLabel1.Size = new Size(63, 21);
            bunifuLabel1.TabIndex = 3;
            bunifuLabel1.Text = "Nombre";
            bunifuLabel1.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGradientPanel1
            // 
            bunifuGradientPanel1.BackColor = Color.Transparent;
            bunifuGradientPanel1.BackgroundImage = (Image)resources.GetObject("bunifuGradientPanel1.BackgroundImage");
            bunifuGradientPanel1.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuGradientPanel1.BorderRadius = 1;
            bunifuGradientPanel1.GradientBottomLeft = Color.Transparent;
            bunifuGradientPanel1.GradientBottomRight = Color.Transparent;
            bunifuGradientPanel1.GradientTopLeft = Color.Transparent;
            bunifuGradientPanel1.GradientTopRight = Color.Transparent;
            bunifuGradientPanel1.Location = new Point(164, 1018);
            bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            bunifuGradientPanel1.Quality = 10;
            bunifuGradientPanel1.Size = new Size(200, 18);
            bunifuGradientPanel1.TabIndex = 2;
            // 
            // bunifuTextBox1
            // 
            bunifuTextBox1.AcceptsReturn = false;
            bunifuTextBox1.AcceptsTab = false;
            bunifuTextBox1.AnimationSpeed = 200;
            bunifuTextBox1.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox1.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox1.AutoSizeHeight = true;
            bunifuTextBox1.BackColor = Color.Transparent;
            bunifuTextBox1.BackgroundImage = (Image)resources.GetObject("bunifuTextBox1.BackgroundImage");
            bunifuTextBox1.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox1.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox1.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox1.BorderColorIdle = Color.Silver;
            bunifuTextBox1.BorderRadius = 1;
            bunifuTextBox1.BorderThickness = 1;
            bunifuTextBox1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox1.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox1.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox1.DefaultText = "";
            bunifuTextBox1.FillColor = Color.White;
            bunifuTextBox1.HideSelection = true;
            bunifuTextBox1.IconLeft = null;
            bunifuTextBox1.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox1.IconPadding = 10;
            bunifuTextBox1.IconRight = null;
            bunifuTextBox1.IconRightCursor = Cursors.IBeam;
            bunifuTextBox1.Location = new Point(12, 46);
            bunifuTextBox1.MaxLength = 32767;
            bunifuTextBox1.MinimumSize = new Size(1, 1);
            bunifuTextBox1.Modified = false;
            bunifuTextBox1.Multiline = false;
            bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties45.BorderColor = Color.DodgerBlue;
            stateProperties45.FillColor = Color.Empty;
            stateProperties45.ForeColor = Color.Empty;
            stateProperties45.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties46.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties46.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties46.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox1.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties47.FillColor = Color.Empty;
            stateProperties47.ForeColor = Color.Empty;
            stateProperties47.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = Color.Silver;
            stateProperties48.FillColor = Color.White;
            stateProperties48.ForeColor = Color.Empty;
            stateProperties48.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnIdleState = stateProperties48;
            bunifuTextBox1.Padding = new Padding(3);
            bunifuTextBox1.PasswordChar = '\0';
            bunifuTextBox1.PlaceholderForeColor = Color.Silver;
            bunifuTextBox1.PlaceholderText = "Enter text";
            bunifuTextBox1.ReadOnly = false;
            bunifuTextBox1.ScrollBars = ScrollBars.None;
            bunifuTextBox1.SelectedText = "";
            bunifuTextBox1.SelectionLength = 0;
            bunifuTextBox1.SelectionStart = 0;
            bunifuTextBox1.ShortcutsEnabled = true;
            bunifuTextBox1.Size = new Size(151, 39);
            bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox1.TabIndex = 0;
            bunifuTextBox1.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox1.TextMarginBottom = 0;
            bunifuTextBox1.TextMarginLeft = 3;
            bunifuTextBox1.TextMarginTop = 1;
            bunifuTextBox1.TextPlaceholder = "Enter text";
            bunifuTextBox1.UseSystemPasswordChar = false;
            bunifuTextBox1.WordWrap = true;
            // 
            // Registrar_Paciente
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(583, 534);
            Controls.Add(panel1);
            FormBorderStyle = FormBorderStyle.None;
            Name = "Registrar_Paciente";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Registrar_Paciente";
            panel1.ResumeLayout(false);
            panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)bunifuDataGridView2).EndInit();
            ((System.ComponentModel.ISupportInitialize)bunifuDataGridView1).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private Panel panel1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private ComboBox comboBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker1;
        private PIA_1._0.RJButton rjButton1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private RichTextBox richTextBox1;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView2;
        private DataGridViewTextBoxColumn Alergias;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private DataGridViewTextBoxColumn Enfermedades;
        private PIA_1._0.RJButton rjButton2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel12;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox9;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel13;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox10;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel14;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox11;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel15;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox12;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
    }
}